'use client'
import { useState, useEffect } from "react";
import { supabase } from "./supabase";

const C = {
  wine: "#6B2D3E", wineLight: "#8B3D52", wineDark: "#4A1E2B",
  wineAlpha: "rgba(107,45,62,0.08)", gold: "#C9A84C", goldLight: "#E8C97A",
  goldAlpha: "rgba(201,168,76,0.15)", cream: "#FAF7F2", ivory: "#F5F0E8",
  sand: "#EDE7DC", sandDark: "#D4CAB8", text: "#2C1F25", textMuted: "#7A6570",
  textLight: "#B0A0A7", white: "#FFFFFF", success: "#2D6A4F",
  successBg: "#E8F5EE", danger: "#8B2D2D", dangerBg: "#F5E8E8",
};

const LOGO_B64 = "iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAABCGlDQ1BJQ0MgUHJvZmlsZQAAeJxjYGA8wQAELAYMDLl5JUVB7k4KEZFRCuwPGBiBEAwSk4sLGHADoKpv1yBqL+viUYcLcKakFicD6Q9ArFIEtBxopAiQLZIOYWuA2EkQtg2IXV5SUAJkB4DYRSFBzkB2CpCtkY7ETkJiJxcUgdT3ANk2uTmlyQh3M/Ck5oUGA2kOIJZhKGYIYnBncAL5H6IkfxEDg8VXBgbmCQixpJkMDNtbGRgkbiHEVBYwMPC3MDBsO48QQ4RJQWJRIliIBYiZ0tIYGD4tZ2DgjWRgEL7AwMAVDQsIHG5TALvNnSEfCNMZchhSgSKeDHkMyQx6QJYRgwGDIYMZAKbWPz9HbOBQAABcO0lEQVR42u3955Ml2XnneX6fc9z9qrihMzIitaosLYCCJACCAAWoQBJU3c1pdtNmXuyLebWv9tXa/gO7a2vWtjZrtmszY7Ozw24OySYE2WxKEBoFUQpZMnVmpAod98ZV7uc8+8I9IjNLACUyszKrng8saSwgKzPihvv5HfkcUVWMMcaYt8vZR2CMMcYCxBhjjAWIMcYYCxBjjDEWIMYYY4wFiDHGGAsQY4wxFiDGGGMsQIwxxliAGGOMMRYgxhhjLECMMcZYgBhjjLEAMcYYYwFijDHGWIAYY4yxADHGGGMBYowxxgLEGGOMBYgxxhhjAWKMMcYCxBhjjAWIMcYYCxBjjDEWIMYYY4wFiDHGGAsQY4wxFiDGGGMsQIwxxliAGGOMMRYgxhhjLECMMcZYgBhjjLEAMcYYYwFijDHGWIAYY4yxADHGGGMBYowxxgLEGGOMsQAxxhhjAWKMMcYCxBhjjAWIMcYYCxBjjDHGAsQYY4wFiDHGGAsQY4wxFiDGGGMsQIwxxhgLEGOMMRYgxhhjLECMMcZYgBhjjLEAMcYYYyxAjDHGWIAYY4yxADHGGGMBYowxxgLEGGOMsQAxxhhjAWKMMcYCxBhjjAWIMcYYCxBjjDHGAsQYY4wFiDHGGAsQY4wxFiDGGGMsQIwxxhgLEGOMMRYgxhhjLECMMcZYgBhjjLEAMcYYYyxAjDHGWIAYY4yxADHGGGMBYowxxliAGGOMsQAxxhhjAWKMMcYCxBhjjAWIMcYYYwFijDHGAsQYY4wFiDHGGAsQY4wxFiDGGGOMBYgxxhgLEGOMMRYgxhhjLECMMcZYgBhjjDEWIMYYYyxAjDHGWIAYY4yxADHGGGMBYowxxliAGGOMsQAxxhhjAWKMMcYCxBhjjAWIMcYYYwFijDHGAsQYY4wFiDHGGAsQY4wxFiDGGGOMBYgxxhgLEGOMMRYgxhhjLECMMcYYCxBjjDEWIMYYYyxAjDHGWIAYY4yxADHGGGMsQIwxxliAGGOMsQAxxhhjAWKMMcYCxBhjjLEAMcYYYwFijDHGAsQYY4wFiDHGGAsQY4wxxgLEGGOMBYgxxhgLEGOMMRYgxhhjLECMMcYYCxBjjDEWIMYYYyxAjDHGWIAYY4yxADHGGGMsQIwxxliAGGOMsQAxxhhjAWKMMcYCxBhjjLEAMcYYYwFijDHGAsQYY8x7TW/Zn5TYh2nMHXpp3+y9FbGPx9yBR1CrZ01e8882AjHmLn5vtXxp5U1+bb/Mr+sl6i3tLZoP+JhDBDSSD3tABJHqsXvnz5iNQIy5reEREXFoGLF17WXdXDlJf3MN56E9tYfm5H6as/cJLiMSy76h3jzVIOKu9xqNebvBUT096+ee1Zef/gr9tXXaM/Mc+8ivMbHnEVHVsn/zDp6x8l825v06ZL/xJRLuYEOsaPVKdq/8RJdOfh0dXaFRV7JUAEdRQD8P+NY+dh3+FerTRyUqOMsKc4ueQBREhM7SC/qd//h/4dRLJ0gBFWHh8MN8+g/+T0wdeFKUiLyDCSkbgZj3Z3DITmK8JjJu7JPdzn6fIBRcfem/6uaV77J71wytifvBKZEcjRGJAWLB1sZVrr7wvzJ9+Fe1vfcj0ll6WXvXXkFcwKVtZvZ9SKS+y36u5h09h6Asv/ItVhZfopnVEJRClcVTz/L8P/0vfOqPHsBnrXe0JmIBYt5HYjnoEIcQ6Fw5oWuLJyiKPuO772f24EcEqQHxtgZIVMWJsviTr2h/5YccPnYfLqkzygNaBLxziASiRkJQmhNzJNkWSye/zNVXv6WJW6eeelyW0B8WXFx5Vhce+n2S9mEpv3ZbujRvhSAixOEGm1dPkeBIGkJRgItCjJ5L507QWTmvkwsPyvUxswWI+UB2uMoXpti6wsUf/6Vurj1LzZWvxJVLT9G9+GM9+JF/K9SnEI0gt6EhVsWJY+nlv9be4jc5/NBxkEiR9xFJ8M7R7axT5D0atQZZVqfIc5J6jZnd42yuXmZ6dg8uGScSaTth7cpFVs9+m7mH96MusdUQ8zZG4sKgc0U7y6cQByqxnCIVIfEO4pDR1tp23Lztv8ICxLxvhusqQtG9pCe/8f/E6zJ75ucQ78E5EiKL509w6YW/1r0f/jei4m55Q6waEPH0ll7Sa6f+nvuO7SGqR0OOcynejbh26Qp50SKt7+Ly4jkmm8LE3DzDEJCsztTCIcJIGY02oRBEwScp6yunmRlt4uvTN0xNGPPTxh+lUW+F/uYyRVBEBNUACF6UmofEheoNevtPlY2FzfskPkC04OT3/xMxv8zsnn0EhbzIyUNOkIy5hQXWLz1NsXVNpZobvqW9PYQ46nLuxFfYvTCLb40TYwEKXiLXzl9AsoMc+PCfyMLj/14OfuRPWB82Wbm2RJpkxODIR6Py3wmRGHLyokeedylGW7aj17zNd6KMg9Ur59lY26IolBDK5XIV8KLUmw3S5tQNb5EFiPnAjdTLudvlC8/oxpWnmJ2fYTjqgwS8F7xLCAhJs0HqhvTXr77T9+WnB5g4ls9+R9N4iam5PYzyclSUpjXWllYYxQnmH/4d0WwKRcjaR+TQh/9E1nrKoNtHXAbqUVVCKChiTogFFIEEh+2YNG/riRQh5F1WzjzD2uaAUfTkEWIQiA6lYGruMI2JfbK97cMCxHwgXxS04NKLX2dsvEkiHmKBKNXWREFEQTxIwnDQvfV9PRGGvWVWzn6bPQt7KTRHvSBJxmhQsLraY+7BL4Jvg4bybIgWpGO7mT7wGVZXVkmdQ6MQg6JR0aCgnqiOLGva/l7zNjpV5Zmi7vJ5vXj6GYo8EkO5gB6CkBeK8ymz+x8jaUyyfbDQAsR8wF6Uct62v35RhxtnmJ6eIUTBiUdEKP8TESJOAs4p4vwtzzCA1dPf03rSI2lPEIoCYiBxjmtXz9GcPk5j6pjcWE5CxAPK7n0fFWjS29iEqBRFIAYFFdAUlYSsPon49N4N+df+0jf5Zafvb9Fn7dAYufziN1lbugTeI0Q0QlAYjYZMzB5i4ZHPAyDvcHRrAWLeF1YXf0LND6jVGqgIzpU7shDwKBIjWgxBod6cvMUJJuSDNdYv/YDpvXMEjYhCgmPY2aCzWbDr6GdRpDzctfPaSTn1VRujkDG2NtcIsSDGnAioOKJAjCBpG+9r904DthMI5ff5ul9vWtbleq0mpZye1DcMGfNmn79qOSLuXntBTz3/t4yGAe8haih3BIYcTRIOP/lFmrPHRTWivLNOVXJvfkTVtMGNdVyEssdWvZRvPt3BDeUibjgPIMI7nQc0N37E8YbjS+Up2DuxY2hr7SL1mkdcgmiBCDjnyyksKZvuYlSQjyBpjN/K1xVB2Lz0rCZJj2ZrN6Eop6iStMa1i4u0dz1K1t4n6BtNE5QjDecBdYQioKrE7f8eQYuIT2vgkhsa5Luv0aIa8b32S4zFCA0jhAhaoLFAQiifFAHBifgElQTE43yK+Kws4fIG0yp6w/t74/+qN/zeD+x7XJ2DioMNTj/1p1y9cBonHqdlawdKXgw59sjHOPqR3y5HwRrf8SN1bwVI1aPZ2T/z2sZJftbr9drf628Om3Irz0//98yb/my2F5Llhk+t7A3drm2nZU8rFgOG3WWmWmMI4FxSdvLFs32YyjvHVn9ASCbwtbbcmh9rLAMyDOhce465XRP4KGW3xDmKfMRgENn/0M9VMfPaz0ERHJp3qUlOmtaJGolRUY3lOgiRGApckt4Yy3fVzxypRntAKAboYIO8c0231s8SBh0G3SV6nXVCzEELYsjREIiab+eAIglRBe8zsuY49eYYteYYkrZI6lO02ruotaaQbFySrA1J7Q0mUHQnXZQbs0c+MO8g4iAvuPzsf9QLz38LKQJZ4ohRESfk+Yi5XfM88Uv/LbWJBSnfz3c+EXWXB4jeXMjoxh6GFuioSzHsqNMh+WCDYX+VYrCF06JMVc3BRZBkpycsJPisSdacImnMgGuC8+LSOiSt6iORN/9aPmgP5VseMpfB0du4Qn/lrCpKa/oAjcm9crtPfodRh2K4Rm28UY4IpJoqkrKJFi13Yg36fVozx0lq7eo8t7z791WE3vo5daMl2nv3kasQJZB6x8bSCvWJw9QmD1SB5d6gtwiD3pLm/S7ZREYIYecPj6EADQQNiKtVn2F8j5893R40VWtMoKMOo83zunHlJborZ9hcvsCwu8Kg2yHkfdBArkqIkaiKRohaVoYtOSIBcYJTQAJOhCTxJIknTRuktTFc1sSnTR0bnyVrTlMbX2By9iCuMUvW3iW+1gR54/e33Kmnr+90vq/CQ0ADK698RU8+9TX6nXVaNU8RlRBhmAfSWsIjn/195o//gmy/K+9Gcpc2SdvzH9czQwuK3jqjrUXtrZ5hsLlI3u/Q764TwhCNI4IWhFCUdYaIOIl4It55nAjOe3yS4H1CktVwaR11dZKkrvX6GL7eQpIWtfYeXH0XmoyR1tqCb5QfldxYSSlWIyIH7+cH86f+jLQaBXiK4Sbnnv6qXnr165Cvk4iQ+wmOf+zf6PwDn5fbUoGqaoDjsK+ZjySZ35nKFHFlcAioE6JAyAumdx0uOxK34iS6lCOCzuXnabYn0GQMHQ1wChKUQW+L8cOfA/E789JvpLf0Chp6hMIRNVbz/gHVSBKl7Ok7V7UT8p5dH7I9TYWAaE6+fknXF59i7eLzrC8tMugsUQy6hKAEVaI43M6Jm4hsl+uTWM64O4c4B1r+UhF0550vzyqMChiOhminR4yhHKwATiFJG2T1Ji5rMj6zVxutSVrT+2nvOkY2tpvG+KxI0kJ8ctNUqlZTrdf/yd2jd7KU71/UqmJzMWDpxb/Vl7/9v7B29Xy5ay8q4sEDzUQ59tEvcPST/1pwSblw/i6/7eSu+0CqXl3ZWEdGm5d0a/klVi4+y+bVs3TXrxKHffIiB5/gkxreCc47fJriXNmIuMQjSQbOlW28rx5Q51BxhCISQ5/IgFEMdEKOxoCI4JIaztVw9Rq1+qRmtWla04eRxhxpa04ka4Frlksu283izlTNB2F0ohDjzm6m5fPP6unv/X8Zbr7C+HiTbKyGiwn9fJ0T3/5/05w5oOO7ju2Ujb7Vn8+ov0HitPx5iyBeiFWDLTi884RRzjDPaM0cvEU/oXJSqhissLX2Mnv2zREi4DyOlGLUJRQZrYnD1ejjDaaeqh5jf+00zuXEmBNCrF6DCCFSqBL1xvpX78UU1vX3UjWQr57UpVe/zqXT32Pj6kX6/YAIeHHgfTknJZEYC1SUpHoFRVJ81iDNMsRRbnSotlmrKiGWHcBQBDQWaMgJhRKCEKKApDjniCIUTiiCMOj1kV6XzdVFHJE0rZGkGbXWBK3xOc0a00zsuY/a+D6ak3uptabE18YRl7zxFOz25yt3+3usoJEormwvB2tcfe4v9ZWn/oLVK5eradDrk8nOjTj60Md57Jf/e2qt+Wrd493vobprAmSnhyYQiy36S6d1+ex3ufjq9+msLDLs98hjxPuUxHmyzONQICDO41ws541xOOfwCE5cufDotFxQFUicxzkHUgaKUyU6h8ehOqIoAvlgi1CsEcKw3I6J4HxCmrZotae0NjlPe+5+svZ+auPzSDIu5fTXa17x29Rgvrf5XjXMzjPausrZH31FL7z094zVAzPTk6gKIUIgUm+0qHfWWTrzY8Z3HdsZudyqBc7tP6u/tUqMI3ySUcRyAdv5cgEacbg0ZWtrk8b0QZKxPbdk6L79Q+6tnNG6D2S1cYaxKJ9FEjq9nHTqAXxj5obn4PV/QBxuMNq6SuIdWoRyE0Ise5Yay8V0J5Ak2fVBz3swNaKijDbP6upL/8Diy//CytJlhsOCqCkOT16UAeBcQS111OsZ9fYMrfYszfY07Yk5knobfIOk1sIljZ12WsQR44gi7xNGA2IYQhgy6nfo9zbpbawy2NpgOOyQ93rk+bCcAsOXv5zHJynqIIoSQqS/ucpgcxmXeK5d+BHe12i12iT1to7NHKE5uY/6xG4aE/P45qyk9UleuzCmO2uuN1wI9p6F+Gun4yg3HGhkcPV5vfDMf+bc8//M5uZ6uRlBFadKUU33H7z/Izz4a/9HarPHZPuOmlsheW/bIy33JmuZoloM6F55Qa++8i9cfuU7LC0tMhwGRBLSNKOWZXgvVe9BIebEIpBTHrZyvtriJwlRwEWPuPIhCDHinJCHAodHvCIquKhIzImxIMRQ7thxihMPrgY+oShy+v0h3c0eS1cvgXsB579BqzXB2OQM47NHtDlzjPrkAll7j/jaNLjspgfupofxHrogaGdHlYZyyVcc5EMun/yGnn36yxS988zPTJAgjIoIvlxARsrCbWmjTmf5NNs7kETlFn7r5R9UDHogiks8rhDElc+TVGdBfFJjOMqZ2Psoztfe9VWeZQCV0yCbV16iPTlT9gRViRGCg2I4or3vQLWQr6+7a6F8iT1bq69oMdwkbTiKWJSfjypKuZAuUXEIrpZV/6LcgUdHy1FENbUT8w7dc9/UC8/8LVcvvUx/EFB1BM0IBUQdkqYwNd5katc8k/PHGJs9QL21n7HpA8S0QVqfFJL6W3/uNaJxQMj76GhL46hLv3OV/volJN+iu7HM5toio/46W511Qt4nosToUZ+VQZ44Eu9wSdllGQ06jIab9DYuoQpJluLSOs3WXh3bdZh0fDftyQXSsTmy9ryIvHbX2/Z7fH2m4Y7sMqz+znIa0O88u0X3ol59+Z8586O/4crFU+SjId4nqEa8i7igpBLZ/8BHeOiX/nvG5p+QslL0rft639MAkaio84gog9VX9coLf8flF/+R9eVlRoMhkFLLkrJH6coFxKIQlCHeFyTe0ailZGmCr23v3pgmbUyQZDW8T8u58Jt6DgENRbkIH3qEUY8YAsQREgtCkTMaBVQ9KIQQUAXvEkg86hLyoiAfKv3eKsvLS/izL1NLG4xNNmlP7tXJXQ9Qn9pLY2IfvrVHXH2iPHl803BZbxic3L1hIhoIOLx4BGXt/DN64bm/ZOPaCcbHm7Rm99NZX+fa8iKt+hjt6V07C9jegzhllPdQjVVjeutFzcuwcB7nZWdqzbkE71NCMWIUm8zNHrsljatUu11G3csahldoze8mFKPr8+pFThFzaq25n/LBOiDSW3oRkSEqDQhx57/fXvSNsUCcI/X1O9fv3V7bE4gbp3X15f/CmRNfZ211jaiOoJ5hEZCiT62esXvXXuaPPMzUvo9Q33WUtLVbJGnvvHH+hrePm1ci3rBDsP33i2+S+CbUZwSgNvsQk9s/86KP5l2KrVXdWDmLjpbpriyytXaJfvcKYdRFYyQUgViUU2b4BO8SvAfntfxripzhxhkGqycRcVwi4hpT1Mf3a9qcZXz2ALX2PI3pvZI1pqrDn2/SrdDrU5uvnyeVtxjcr/2whLhzINYBgbB2QdcvfJ9zJ/6JS68+x+rmsNw2LilBA84reaHUUs+Dj36Wo5/7P5DNPSrbo9lb+RS9RwESq7UrB8Mtll75ez3z7FdZvvgSxagAl+CyGl4hOgEVVAti4UgzT6vdojU5xczCUeoTe2hP7UHSNuqbJPVJkmxcJMnKHgLbi3jbB5EKNIw0FkNi6BHDFl5HaL5F3l8hH3QY9dYYdlbod9cYDQbkwyG9YlgWIguCqCtrLCVUwRDJY2Rtucvq8gucP/0yjUaTsbEWEzP7tTl9mMbkftLxPdTH9wrJGDcPhvU1b9d7HSjK9Wu8PR7oXntBL/7k71m++F0ambJn3zxFAdeuLJGN7WX+yIOsLT5FmqZlsTaN5cvqcqKUC6fgb1N7F0EdIgm4UD4/1a49STJ6G6uMTR2iNr5PbsU80HYTsXrhaZp1cL5OzIcoAe8SRr110myepLHnTWoMlX9C7K9QdBbJ0owQPKLV3L9qWXq7Wkz3kuCTxh2YPtneYeWQmDO6/JReOvE1Fs+/yqDfw6UJo4FCPmSi4Znfcz/z932cyYMfozZ1XEhaN4xYtZqe0p3zVTePPuWn9VquLxFXdc5kZ+xX/ZakgUsa+MYumZu9H4C5YkQcrrK1dk5jf5nB+mUGG5fprC0yHHQIRTlFrZpCFFySkHqPS7TcYKNCJBBCh8HSD+nlOcuveKKr0Rjfra4+TWtyD2OT+0gb0zQn50mb05LU6iDp27rxcqcDedPvlzf8f10ckncva+faq6xfPMG10z/k2uJZNrt9cnV4ylPmMSpBgWHO5OQE93/y1zj2yT8mGT8kqrc+PN6jANHqwh1P3r2k55763zjzzN/SWd+o5q6TsoaRy3Hi8Qouc4xNTjE5d4CphYeZmL+PZGwvtbEFIW1VW/feymTH9X98o6asphGVgIQeob+iGgYwKoe8g81r9DYuM+wuMRz16W0NyEcFeYjlBS3qSMQRNYGo9Dtd+hurLF08g8++T1Jr0B6fpTV9QJtT+2hO76M9fQzf3C2k9Z0dXrLdIN7wVcsdmfjWqsyzq0Zt5X/bufKKnjvx96ye/TbObTIzO0fiWmwsLTOMMH/sV9j/xG9LvrWqm1dOkPhauUmBgiSpU0v75M5f/+bkdnzlVQPjAPU727ajF9RDf7PH9NEHy9/wLqevqokL8v4K/eWfsLBngnzUp5p0Ao0U+Yi0dQRJaj91XrC/8pLmw24ZDqEMDmK5oFyug0RiiJA4XFLjFh1e+amNmoqD0TpbF76rF5//L1y9cpEYI6l4ClXG6jB94BB7j3+C6UOfxk3dL0i6M3LYbqOuP7PyDna+u53ffvOzf2MU6w2j+eqTSTJ8Ms94a75agszR0SbDzUsatpborpyjt3qe7sYViuEmRT6gcCkxOryPBF+eF/JJk7TWwEmsFvqFUGxQ9FfpdV9i42wkaEbWmER8S102zvjMXtJ6G5fWaU0sUB+bwaUNUZ/hfVZOu7sbtxjLTR1qjQVa5Ag5GkYMO1d01LnKqL/K2pWzbFw9w/Klk3Q3u4yKWM6QuJRElUgkqBCKEV6U+X0HeeLz/465R35VfDZRbfC5Pc/NHQ8QrcKjv/yKvvSP/x9On/jn8qStT1FRVMpD9VEDtXqN6V0LzOx/iNnDn6A+cxzfnBd87fqRqqq8gb7p0PFnjxi3p1y21ybUT+DGJnbyenwXjMchYbiBK7Y0768w7Fwi7y/RWbvEsFPOw251O+TDIaHIy+kMBY2Ooj9i1BvRXV1Hzr+K90K91qA1tUB9ckHbuw7TnjpCc+YISWtaXNp6k6/1hu/zXZ1H0eszBTuDHmF7zjcWPVYvvKwXXvonls79kCRuMjUzTq2xl/7mBt3+ChN7HuXhx77E+L4PCwi9jWuoxPIlqdYeXOJxaUKW1cutmrfxmYohEEMOKviqaGKWNMm7a7hkmsbMfaK3YBF6O39Wz3xLW/URvpYxGvXKHS8i4AKD4ZCp+V03/ws3JZAAIwYbJ0EiEU/cPkEskajl8+921krAeX+7X8zyJsfRMmsv/7Weef7rdFZXcQgigSJExibHOXjfh5g59oskMw+K+LFyt5hWByrv6Ar/9QoS8toRVNUoiyRQm6G+a0ZkF4wdCuSDdeLWVe1vXGJz5SJbV19ha+M8IS/QQSSmNVwaSCinrMHhvSNL69SrMBF1RJQQcmLYQPN1BpfO0IuRolDWsho+baIu1eg8tXqbJG0hWUqSZgge5x3Esu0qiiFxNGDY71KM+lAM6XfX6Gwukw+69AcDBsNILBxRMrwvn/lQlJ2OPC+QOGS8Pc7Rhz/N8U/9PmMHPl5+Mhpu29TxHQ6Q6wfO1i4+rT/82n/gwks/wPmUWuYIcUTmMiQKwRfsmtvN7mMfY/fxz9KceUykPnl9dLt9/oByd0j5MLl3/gxWC5fXT6HH18wFC+pq+MYcgKTtw2RzoGHAZNFFio4ONq4y6lxhc/U0/U4ZKp31DfpbfUaDARoC3gHBUwRhc9hlbf0FhBcQPGmzTb01TXNqXsdnjjC95z4aU/upjc1J2pjYCbfX9sHkhjWVN7zvW2+cFpBq98XrZ3JCPmBr5ZxePfssV899n62lU6RuxOTUFPVklkGvy/ryBRrjB7jvU3/C7uOfEedbxFjecOZFcUlZNgRRnNve9qnUW23E+dtWwcj5hKCKaMDjyt15EnHesbG+SmPmI0g2+S5fpu0zL47++lndWn6avQu7yIshaIEEqjWzSChAarM3bwu9cfoWR+he0sHmeTTJiDFe/2zcdiVVIcZY1tV6kxIht3SbhAh0F3Xlpa9w6sQ36XY6eJdShALxgYX9hzjw4OdoHfyskM1Va0+h3FRx15yhkJ2dXbozitGdXXCKI63PQH1GajMPMXkEQn+VYW9Ze6uL9NbOsH75RYrRCsNhDx1AvZbg0gZa8yiOqNVZFcrp0SQDt3MktZz6LYqcIu/BqEBDQbdTHqCMMVS7b7Wako+EEHa2boeo5CFWhTi1KgsU8T6jXguEpNxhVhSR4SgwCjmEwFizxZ6Dj3H0o7/J7gc+L0ljZmc95naGxx0MkFh1xBzXznxfv//l/xuLJ1/A+wSJwmgkuCSlCENarQbHj3+IfR/+dZr7fk6S+uzNc4Y7/0deN6h9d52ZN5iLfN2UpN44sYT4OuLraG1W6q3DNAiM5z0k9Bh0r2norbC5fJLu8nn6G9fobyyztdWjPxwSgxJDRhHKff6hv0lcWcedP0WSfJ9Ws0HWGKc1uaCN9iTNqXnGd91P2pqjOT5DrTEukqTgs5trEP2MuTsADUPiqEdvc1mHnausLp5g7dLLbK5chLBJVkuYnRwn8W22el2u9nJca46DH/kShx75FUmqxWHd3tEhZa9se47bi5Tx7qoDX43xnUN3t0NWayNpbeekcTkF6hn1NyhCSnvvE7egzplW7VDByit/z8SYQ1KP5KOyYYhAjAx6PZJ0irS9IPJG6y3VZzRcP0Pe66AuI8RAjJHES9W4KBpiGSDVciHudjQE16d/itUTevXFL3P+xR/RH4B3oKFHrdni4PGPsfDQL+OnHhdcvdoNxE9ZUL4bokReM+K74R2+YYHaN6ZpNqalOXMc+Bx7BmuEwbp21xbpLZ1j7dpPyEOXUXdIVCXNElLvcGlS7ghVyoZelaChDAp1iK+hLkNcwMWIxPJcT1maJqfIpTxsiaIEYiyIMRKjVEU3qinM6s92UoAURAQnkUYdpqcnmJl/kAMPf5aZY58kG98v2+/lnapBd0cCpPyGPBsXntEffuX/ypWTz5K5BrjtA0RKMRwyt2uMRz/zO+x97Eukk0dlZ47zrikfIm84FSQ7z6VH0jakber13QLQ2PtJFuKAUW9NB90lekun6C6dpLN2mdWlK/Q6G2z1+mVPAwckxOjodIZI5xrrS4sQFV9LcGkdn9ZpjU3SaE5oWmvRnl6g1t5FUi8PR0XSnV5HuV0vVv2xnDjs0Vu/xMb6RTRsMequVFtgIy4RJqdqpOkcsRD63VW6o0itvcChj3yK/Q//KvXxhfKx1rLUhIjbmQdThKIQYlGAL3CSIarkRUGatW+aJrnVP42sOUGS1Mvv2znUKz6BzatXaU0/TtLcI/FdzgNvd4A2LnxXpX+W9r4FitEQYrVeESMaAyEfIu0JxGdvsOBdXjBFsUFv5VXyKAh5VafIkfiEwSgQo1Qnzj1CwEs57XFrl8+3IzUyvPpjvfiDP+fC2RcJWiAuIS8Ck1NTHHn8F5i574tofY9EAaf3etWF12yDVq3ekYiSkNSnSOpTUps8zMzhT7O32KLod+isL2rYvEh36RRhtElebLLV7YADTyBNPM6liHc7pdF3LgDTct1XVcvR5vY/V7MyZXmXSAgFeRHRIqBBgAKVHEdEXCSrN5hojdGenmdi1yGm9n+U1sKjkjTmdjaTSFUZ4k65bQFSHZPaWTDvrZ7SH3zt/8HFV57HpY2yvAPloq3GATO7F/jQF/4b9j3xB4JvXQ8Oqbb03a0P4007R/SGHk5Zj8n5GuprZBMTkk0cYnzvRyDkjHorWmwt01k+zdqVl+hvXGNjeZGtzjrDrS00FuWBPE3K3mcEHeRoEdjsb9ClrDi7lCa46nCkRkFdUpa9UEGkCg/nwDmcCN4FxJX3bGdZjdrkGLUkIWpkMBrQ2VglapPm5P3cf+xT7Ln/U5K1rj+g1++xeINxplbbTgWieLQQRqMRuMbtfYizBt6V89XlZ5EQB32GhWNqz4eqmSHlHd9eUB28yjvndP38v7Brbo4QPRqK6sRv2TAQcjSOaE3MU+44i6+fThQoNs9rZ+1COUqL5fMSQ0GOoOqqnUfbNxAK+Opc0y1d7xAg0L/0lJ757v+PS2dfonAC6hEdML/3IEef/E3GDn5WNJvZmRRSef2ZlnuabB9IdFS9IxDd6Rq6pEXWbjHTnhd4kjkCWowYdpc0760x6Fyhs3SWVLugfYaDTbT8SaJhSAhDYig3Q0SUWASKoiwmWV4atn0AWkFzPAElol7waUJzbIr2+Azjuw5SmzhAe+4ojcmDpK3dgqu9JjgceofbyuR2Nq1l6QpPsbXCc//1/8XZF76Pelcewa9ui9OiYPe+3XzoV/4de5/4fVHf2KlTdLt3ndyeQbPcMAMmN8zD3vDA+oysvSBZe4Hm/KPsfuSLhOEmw+6qdtfO0Vk6Sd5dKesLbVylP9hkMOhDDNUCukCS4b3DqSvXglwsD9173Tmktt3keJ+VdXEk4r3HJSkChBjQUZduzxF9HZ9MMHPww+w+9nNM73tCJBu/PoKEn3p6NcaASLkeIlWJDlFPLCLqbu9A14lDnUOqXqD3NTY310iau8jG97xxIcO3OPW6s74WB6yd+mfa7QZpo81o2C+vqapOjocQkRAZ5SN8NnbDyPt6cXsVQWJB5+rzbHXXyo0jCPiUemuefLSBuj4a5Ya1Pock2a2b/KvCI8Y+3XNf15Pf/89cO3+SgoyiyPFuxJFjD3Lso79Lbc9nBVe7aR3n/VsmXW6YGX/9wvxO/otHkgb1yQNSnzxAm8fZdT+gOcWwSz7sqhR9iv4Kg+4lNO+CBjSMylP2xZCiGBJiTgyxmkT0eJ9V9foyfG2M6BJcNs3k7GGSsV1kzWkhGXv9z/I17+Wd/uncxje7nK5wMefk9/5UTz3zd+XyZrWwWg7rcnbvneHDX/hj9jz+e4JvIBpu6TTHXTlsvqHs9Pb0j69N0qxNSnPmCHPHPgcxUAw2yQcrurVyjtHWMqPeGqvL5xl1V4mjDsP+BqEY7ZwSjwghD9UfXR6GLGdtetuVzUHBuyG15jS11gzjU7tpT+6nMXOIsbn7SMfmZPu8hsZ4U6nun9rUhhzvI+Kl3HClkUIL8H6nDMdtWv5la/0s4nLSxhgxD2U9qiTB03j3i4hVif+Ns99Qicu0p+fIRwMCQqzWPWL1i6KsNOskfdOvVrsXtXPlOXQ0IPjISCNj7d0sHPs8nas/5NrFF9iuDbU9A+IkRaO7ZeGh+Qbrr/6NvvyDv2LpyhWQGkWRU08Cxx//KIc+/EckM09IFIej4B69NuiWv7vyRu+vVlufJd2Z/tr+XTc191ouqBMDqkW5e+16F6i6t0aqZ7f2hqPl66fgq4KTd8Hmhds3hVX1glfP/EBPPvVXFMMhiU9RjQQRYhEZn2zwoV/4PfY+/oeivnlDeMgH5qG8voaiNzc1zpM0p0iaU9KYPrbzv+wbbaH5FoPuig42rlWn6bvk/U36vU0G/S4h5uWZyVgWrHNOyBotGq0Z6o0pXNYia++iNb1AWpsWueGmu/J+hog4KQ96vsVmPIQc51y5PbGqpKoo3nuSrH4bPsOAiEc1p3P1J0zPTJclz/0AJVBv1Nha6hJGXXw2zjs5gKdRECcMVp7TwcpzTMxOMyrKaSupuquh6gDsVJZ1fmfNTna6tFpOLWikc+1pOpvL5Z+fF4DSnj1AbeqwdK7+UIuQ4yQpF+YpKwFkaYa4VOAdHiPc3uYuDh2usPTSl/XUU19jeWWd6OrkxYjxlvDox36V+cf/NdI8VO5ZUn1LZ6w+uKGyvetLX9MprJZvbyigKZIgSfIWRwm6cxbsxrGQyM1jwbvB7Xk6qu26RX+FV576X+msXCRLPSEWJDFBVNAs8MATn2bhid+nDI9427ec3d1rKG/w/742VERIsjHIxkhbu6W9+6HXfO4BjeUc6mtHDVLd9vbGPy69frypvJHpbT+ioRjgXTkUj7EquKihLH5Za97yAfb2NH732isaBytMHj5GjEPEBSCUxfVilzBYV5+Nv4O/OCLOkXdO6+bZf2JifBJiQowFzilbnQ6o4tOUqEVZLYEU5+tv+pMOg6u6fOlHhLwsABrjgNrYOJN7HkddnRjK7d7l5pJy56In4rNaudvuHQyflHLbqUMYbZzRpZ/8OSef/SYbnS1yEvJhn10TTR75ud9k9+O/R0wXZHursV158zbf49fs5pQ32XTzlqbD32R0cbdNId6WANne33HpJ/+ol178AUEFX+1Sct7hQ8Hc/v3c94kvkTT33NLqkO+v51LeIF8i213c8uT4dm/IlQf4vH+TR2y7V3PDkUupTpa8q8KC5V+fj3rlQrZPy11d4pAALq2RZq1bGx96fV1h8/LTTE41kKwOeR+HBwLOe8T16aycZWb8wNs7gF7tFouDJZZe+RuaqYKDIg7Lmw03uqwtr9BstWil6c7UgqLlLpybttyWPy+VQPfqd+mvX8a5FKUgAhO77yedelg09ss58VBt492prSQktTH8djXed/DDcQTya8/q4jN/wbmXv0+3Fyk0IeQ99uzZxaOf/hJTh39dNJ1F9LUHVc1t6TC+T9zyANkOg3xrhdNP/zXdjQ18mhLUVWXUlVrNc+zxTzA2/6G7ZSrvHhs+Xx8Wv/7woP6UPNq+lfHWf+DFoAuiJIknhLKQYSTH4XBJ7Rb/heUIZ7h1RUfdC+w6OE8eQ1lBuapmAEKj6Rn2r5QTDPJGh/re6E8uDxtKvsbVF/5K07BCMjbJKO/h0pTu+ipJ4z52HXqA3tLzFPmovGEvBkIIiIs4H3f6/+Xn7tDOKd288COKArxTilFkrDXBroOfRpIGob+uYdiDmG9fL0MEglMkraMueYtTF3q9wyAOwpCtxW/phWf/isUzLzEspAyPMOTosUM88pl/RW3vL4lKozpH8/5s6Mw9MwIpH76rZ57SxTMnKKKD4MvdOZQ3qk1NjLPr6Kcga/Nu7+S1XszP+uc7YzQaghNc4gjbi7WuCqzb8vMVNhafoZEFssYYozwvLwvz5bbMED2t8Rl6S1eJ/VV8Y/pnTyFUuwYZbnDlxb9Q8ks0xtvkowLvU7bWlwgyyeyRXxHNh3SXn9FCyyuTYwjEGPAScdvrFyhKgsYevcXv0dtcL0cSRYFQMHv4Q6RTD5VrGzESigFFPizPlVQl8R0O57Jyvect3aVyww11+QaDs/+o557/GouXLkJwaIykLufBRx7k8Mf/mGz2E9Vi+Y2XVhnzngZIZPnM03TXNhGXlT0bVw01woiJPfdTn37Y+jnvI0WR7ywil/fQOwhlddydOk634gdeTS+F/jKdK8+w58BuYlS8JGzXbCx3LClpcxI4RXf5hE7s/4y8+TSW7qwxhd4Vrr38ZfX5NVrtKYYxknrHYGuTwVDY89gXkdok6jqktQlGWxdIkgaaF9UtiAWjrSXqM2UtJokFgyvf0WuXXiBEj0MYxCGTswtM7Ps0ul3XLeYU+aC6wMxBdKjkeK2hwe1M2f3skYfDAbF7TjfP/SPnTvwLayvLeFejCH0aacL9H/0Uex//12jzflHBwsO8Y7f0qSlHE5APOqxePlPtcxZCKIuxjQpFnTC152HS8TnhVlS3M3fFiCjqCJxHnLCTI5TrXrfD6uLT6sMG9XqDWBR4pywtnqW3vl4eYA05MYxot2p0ll5GNYeb6oVVlyZprG7rFgarL+il5/9U07hBe3KOgMf7lOGwx1Y/Z/fxXyMdPyxowKdtfGMfRa9PHJUjh1gMGfSHDDcvIaM1tOgxuPJ9XTr9DQaDDt55IoEsS9h97Ofx7aOCVtuuQ6QoiutlLLQg5gWRUF5p8DOmJ3eqocUR+fozuvTSn/HKM19ndW0DvKfIh7TaYzz+6S+w9yP/HbQe2L4AlHLbtr2H5q4YgUAx6rPVXSsbE6Eq7y3EPFCv1ZiYOwAkt/R6U/Mei4HEuXLxXMrtvIWUdyTduq2g1SG4UYe1C0+ze3YWRiOcU3qbfdaXugy7AxpNQdVTFIHmWJPV1YtsLP5QJ/d9UrYvagIliiunVosB64vf0c7id2m3EtJ6i7wIOJcShh16W8rssV+mPvdkuVmw6vRM7n2UrSvfYxT6aHRoCMSgrFx7GZ99VWOA9SsvMuiOEF/uQlQNzB/6EM2FT0qU8g4QAZwoogVCLA9hIohGvAOX1H766k11FkHCFsXV7+viy//I4plXyUeB1AmjUWTX7nmOfOhzTBz8AjHbU1Ure++mPI0FyJv0RcFLRrMxvnPYJVJOaYSgpPUWtYn56vffvkuGzB0dgKAhkPib7y8p75dIbt1At5qDWrv6krp4jfrU/eR5eRvb6lqP/Y//KzYWn6O7fI7xmd0MI+ASdk2Pc/nVvyXJ2jo298j1UxpFn63VV3Tz0o+Jg0UmxmuISxgN+7jEM+gN6G0F5o5+gdaej4juVEMpLxHL2odkfP4JXTnzzbIicMxBYdDb5OJL30PxaCx3ZmmAUOTM7j3I5LFfQNPZ8uhnVVzREcpzZEpZeE9AY1ljKd3ZBv3aKavqfIkIbnBZO+e/zoVXv8O1SxfZroI2yAfsO3SQIx/6Itn8Z0X9WHm+w7LD3HUjEBGUSNqaYPfeo5z/yTfKEhreg3pyN2TvvuPUpg7cjhk0857kRxUaGnA+wRFxKF5cVZ8nvUWzlGVtNA0j1s98j+npaZJYoElKf3OVpLFAY9ejIumYXnrmZVpjfUgSQlGQ1hpMTQ24euLP2Lr2ojYmFgh5j2HvAjpYoVbLyGamCXlOyAu8eHobm/RyYe6+X6W18BEpL9rSm75vlYTJQ7/AYHORjcsvlhVYtewYhVjekqguwRVKiEOmFvYy/+BvIK37qo/EoW67TkZEXAYuZbs2vEYl8Ul5DqTKDJUbdlnhcBoI3Vd1+dV/4NwL36Gz2SPxQl7kZJnj0CMfZeHBL5BMflTUZzsVi425O6ewqlLahz78W1w58wyXTj0HOJwUtCYSDjz6c6RjC7K9XmLeB7SsJOociCvPlYgIEYf45NaUpokgztG5/KzK6CITkweIoUC9Y2NzyOzxjwFQnzwkY7s/ppcufpd9h/fTj5DHSGOsRZpl9DZ/Qm/zJ6T1Go2sTjLRJJIQQrUNOFE666tIOsOBB3+FZPJBubmm1Q0RooprLMj8w7+tqoGVxVdwGomSVMUQC8Koh4hj1/7j7H30N2DsYRF1r6uXFrUPKJKkOE0JcQROSLIU2Z7CkvKDEPVliZnQJV/6oZ59/stcfPVFQi6ITxmOekzMznD/Ez/P5H2/QagdEKlWpGzYYe7qABEckcDYvkflY7/7f9ZzP/pLrpx+GueUA4/9PLsf+TWUhLJ8srPH+X0hohpwvjzrIyJlRWARfFq7Bdt4tTydHQesnvkuU3OTqE+IwHBjDTd2kNrUEdFqSmjX8V+WVzcv6aXz59m1dw95LAijAKQ0pqdJYtmAR1WKXMEFvHiG+YBeb4va1DFmj3xBXH13WbPozcqXl/vS8WP3yZ4P/zttTH6DtYs/pLe5RiiGeJ8x1p5gev+HmD76i9DcJ+WU1c0NuapSjLpV+RJXHgYVhwTFZw3EN4g701ZVnbLBBd08+w+cevbvuLZ4hSAe0QTydfYeOcYDn/gStd0fF3Vz+Kqel4WHuftHIEJ1Gjgyvv8xeXjhOPetX1ZxSjY5L+Kq+Vw7+/F+GHoAQlQFDeW0lVYH5UUgRnzSLO+Dfjd/R1XmZv3KT9TFZdqT+wgh4kTodIfMHH0ScelOgTrxNQ4/8Qdy6qn/WfNzZ5md2wveIzGiORTE7Yr7OHXkwwHd/gBoMXvgMzQWPipIoxwR/NRpVtkZRUu2IDMPfImpA0/qYOMSoejjfZNGew/S3CvR16vhObz2jhBU0UGHotiuUh2r0PQktQbiXRXTHhdzwvozevXEl3nlxafpdfp4ydAiJ0lH3Pfkpzj8xBeR9hOCa95weNLCw9wLAXLDy6UxIkmd2uxhuam+k81dva/I9n0Y3hGru9UT8RDAJUlZmBHeYSMmZVmR2GP93LeY3TVL8E3EDdnaWMe3D1OfPV6OPnZO6StpbYpjH//v5PJPvqKLF39Cu5mWd7O7WF4CVQRiCOTq8G6csd2P0t77cVxjQcoi7uFt3XshKKoZrnlMms1jr4/ZN73QqryXIxY9tMhRtLxjpLp4KPE18HVEwY2u0r/wL3rmhb/l8rnz5EXAe8dwMGByusXDH/88Mw/9DpoekajV1b4WHOZeDRCcIqpVz7As6lZev2reV+OQ7eMV1QGQ8l7F8kIkl2TvbrRZdTg2LvxIMzq0Zh6iyAdIUqPfK5g4+OFy4VmLG7YLl7VAkmyc/R/+I9laOqOdpefpbJ4hrSZOo0A2Mcv0rgepTxyR8qT6zr4mqpOvbzPoqtMYujO/VZ7ruKH8zJv9q1FH5KMBsYjgpNyAoEAURp1lEreuV17+Kmde+RG91VVEkvJCojjiwOH93P9zX6Sx95dEZVf199rhQHNPBwhVjXuQat7WguP9O5WlO1dpOsRFcGXZGufTd9GQlVM+Md9i48oPmJ+bR0PAJQ36nWskjQWas/dXV4+/5lHeuYPd0dp1VFq7joIOKS/xoDzp+LotxjeeS5J38LxXU0Vv8wpmEQihYDAcEIOUu7c0IqLlwv/l77B0+SwXT79AzANJUmc4ymk06hx57BPsf+w3kPZjojJWTX85e9vMvR8g5oM3ChGgbAMFweHezSHCauvR5oXvaZoMyVr7KfKId4Gt9Q7jhz9Tjj7edKpGqiWGiDgFycDLDdd4aXWFKe/RPd/V162BfNQjH43KWlziCDHiJbKxepWV5ROsr6zikgRiYFgUzOzZw/EnP0X7wC+g6VHZvkLaGAsQc28RKS+Tcg7nU5wK4sqy7u9svev6wnkYrbJ++WkWFmYJocBnGVsrV5Da/M7o46c2/EI1haY7twveVCTfvfdjYy1y8mF5F4hKRKNHUEIsOPvKSxRRy11igy1q9RrHHn2cPY98nnTqw6IyhdxQB8sYCxBzj+WH4L0vF3pdghMtry/WUBZYfAcBEqu2ffn0N7VZ65Kkc+RxiBRDNjo95u771erx/dlz/a+9q/6uGrmhhDAgH3bRWID4nV1toDjvcRrIiyGzu+c4/sQnaB/+ZciOiu4cbrTpKmMBYu696KgCpJyqUr35+s2bRx9vvaEr1809/bXTunnlBxzYN80g36KWZawvrVKbPEZt+qioFtW6y73o+ufhY0fDsE+IOU5jNblW/icMR6T1lPseeZS9D/8K2eSTEpIZHNFqWRkLEPN+yBEPPkMJOCeIA+fKaZfwmrB5S+0q5Xz+tdP/xMRYgvMNRAqKTo/hQJh/8DOyE1L3UgO6fWe2bN+RPiJsvqLr577J8pVTxBiryxa37wIRphZ2ceTRTzJx+DNo/bio1PF2tsNYgJj3A90+35CkhKg4V+7EKltA/7aXQFTKw3vrF76txcarTB7aSxGHJCIsr6/R3v95fG2WG09l3yvpobJdv0qQ0SUdLH2PxZe+x+Wzp8hHfZzL0FheU1zkIyZmZnnk53+XdPZTEtM5ROUt3apojAWIubc4T5GXVZed96jzSHr9dPhb76ILYbDCtVf/kfm5CdRFEhxbGxtobQ/je36uOjR4rywY33jlsODiOmH9hC6f/Q4XXzlBZ6OLF8H7jCLkaBRiVIbDCJmDsQPEZHe1USxaeBgLEPO+GoNQnoBIiPkIkfIkNdulz4shb239oyzpISIsvvxP2qyNqLd3UeQjIsr6Zo89D/8euDrlpRz3wIiDsiIvIohuwdY53bjwPc6f/CErV65CBOc9eVGUZd3xRFECkaKI+CQjydrV+v9OLXljLEDM+0u9NUnsbRfHVGIsIAbyvA8xwM+ohxUBJ47u1RM6WDvBkUP3MYwj0ixl7cplGtOPk00fF33TkiB3k4CWRe1xBOid1d7VH3D51DNcPn+GUZ6TeggSGY0GTE1OE4KyubEBRETAe6FRH0OSxs+6yd0YCxBzbxubmGXjmhBjeWhPJJB4GGxsEmPAueSnjETKE+BhtMm1V/8r83vnKLIUCY582KNX1Dlw5JcEkvJsyV3XE9/+vqq71fFAwA0va//aD1l85dtcPX+a3tYA52o4JwyHBVkr5dB9DzA/v49TJ55F11dwzlXXvivNZhuCszvXjAWIeX/aLv2R1SfIY0FUcDhEhSTJ6A82iKHAJbU3bXzLsh2eqye/ro1an+bYPIMip55kLF28xvS+z+Abs/zs6rjvVXhU95FXn4YOl+gv/1iXTv0Li6dOsLHWRUlwzlGELZJ6wsL+Axx44BM05p5ktPwcw/4WHvBS1sLyLiEbm0GlZosexgLEvM+DxKcMRuAlBe8IRHyS4iVWO4vepPGtznx0rp7Q/rVn2HdoP6NhTpY4OsuXKLLdTOz9hCh6Fy57xGrwUU7dyWiTfP05XTr1dS6cfI61lSXywoEkFDk4N2L3/C6OPPIkM4c/jW8/JsE3YP1lHYyGVfHEWF6ehVIfn0TSZrW1154xYwFi3qeyepukNk6ICmkGMcdnGfV6isb85pmenfxQEEfRX+XiC19lfq5VHsB2kXzQZ+XaJvue/G3U1++uawCq8xxRXFltN99iuPairl/4DpdefYqlpauM8hwhRRViyJmcbnL4wSfZe/xzpBNPSKzNoOJwoy5FdxUtRuV4TgNESDJPWm8C6c5YzxgLEPM+G3qU+4MaEwsy1p7XQb9Do7EbyaFWb4Ms0euuaNaakde2wmVpqpzTT/+51t069dp+RmGLhmtw8cJZxvd/lvrkMVHVu+hGvVBVa/cQB4w6p7V36SmunnmGa5fPM9wagKY4HPloSKtVZ/+xY+x/6PM05z+O1hYE0rJcO0pkQK+zRhiUlYJzFxgVUG/WSaQGKnZ9jrEAMe9nEXEesgmG/fO0fcowD/haEydKd/0ik7uPE6tpKEGqA4iOs09/VftLz7HnvkOMej3qtSYrly+g6V5mj/y8XL8L/C4YeGhZsl5Q8u5Z3Vr8ASuLT7N85TSDrSEIJLUGo2GfegZ7Dx9n/30fYurAZ5H2UVGp7XxeO+dCRBj2OnR6WzhfR4BiVNAYS/CNGZTExh7GAsS8j1WDg/GZg3QvvEJUAfGoJIxPTrK1cQ621zA0lscAxbF05vu6euYfOXZ0oTz34B1bGyusrucc/czv4JJWdRDxvbnf4vqYJ5alR0QIw1W2Lj+lGxe+z/LlU3Q3ewTKi7Q0V0SU3XsX2HvwQ0wf/RRu/D7Bj1Wl7ss7zxV3fQQWhzoYbDAcjsCnoJFiOGIqcaTNiRvuNbEYMRYg5n2sMbmPldMeHfVIxBOLSGt8iuUzF9CiD76OSnlj4eq57+jFZ/6Cowdm8c6X6+lFzuLla+x/4r+h1t4v26OU9y4YyzGTiEPiiMHKc7p88p9Zufgy3e4GGsF5IYaAFjA+0Wbh8APMHPoktelHRbPpnXMxZRD4G4czVSBt0N3qEkcOTcrrSUZ5JEszHFm13GLXQBsLEPN+VQ4tGJs5KL6xWzurl5ic3UORD2i1WmT+KitXXtDZfR8RjUOuvfwtvfrqf+HI4WmSrEaeF6SJcOHUZaYOfo7Jg5+UqBH3njaaWu2uihSbp3T51D9x7dR32VxaIir4pIY4R5EXZLUme47cz+zRx2ns+iiuPi84VzX8vG70IDccDRx2ltna6BDU42MsT9nHgkZz7IbAsfAwFiDmfZwg5Wgho73wAEunvkp7ejdF6CO+xuxMnVM//E+sL57UUe8abnSBo8f3QZIwGuVktYTLF85Tn3uMfY99UVS3jwre4YZzZ3eVlPeiD1dZPf9NvfLCP7J2+Ryj0RC8Ep1jNOqTec+uvQfZc/yTjO/9JG7soKh4ts+GvKUT83mH0aBD4kFcJBIQAtnYBNQnxY6hGwsQ8z6PD9mZq9+190lZPf3P2l9fpj4+y2g4YGxygsMh0Nn8EbPj00xMHiPGSAiBZlpj6eJF6uP3s/ej/0bUZe9B3aftg4BliXgXcvpXn9ZLL/09K+efZtjrE0nKgpEhokXOxHibPQ9+mvljnyedfFA0qd8wunirpesVQg/CiNQLUYAoiPc0mlPgx235w1iAmA8GVcU3ppg79ktceflr3NeeI7qUfFQwPj7D5NQcQQvyWOBciisClxcvkk4+wJ5HvyTRtYBw50+bV+dRnESKzfO6euqfWXz1n9lYX8apoL5OCAVFLKhlnvnDT7DngS/Q3vMxIZ2o4idQTjm9lda+XNPQoqDfXYYwwvsyNF2IJJmj3miD+mr7sjEWIOb9PhKR8ia92UOflt7qeT175mX2HzyM1GrEYkiMeVkoUD1ba0usb/QY2/NJ5h/8ZVGp46p70O/QoGNn5CHiIN9k/fz39eorf8/K1VcohuBcHdWCMBqCKLvn5tn74OeYOfrLyNjeqmmPZSXdt/l1K4JqztbGKnkRy8V4LRBVavWMWnuqfD0VVGwQYixAzAdjHEJ0KQc+9Pty8cW/07NnfsBYIwMJxGJELKA/DKQTB5l/5DcYm39CyrXmchRw577KUO0IU3rLL+r6S3/PtYs/Yqu/hZDgUyiKSAw5zVaLPUc+xNzDv0595mFRl1aDiGqL8dtt3VVQAceQ0aDDaBTwPkWiIgqNWo3m+Fz5eWjcqTdmjAWIeT+PQShXRCLqW+x75Lelv+dR3bx2muHWCpoqteYk07OHaM0cFZJatUP1TlbY1Wq05CHfZO30v+ilF/+B/uYVVIVUPIpSaCBNhOk9DzD/wC8xsf/nRGqTN2yrfXeLEwKE4YaOtjYhlKM3CQ7CkHo9xaWt6iu1RRBjAWI+QBFyvbS5ozF9TBrTx964GddYnfO4/eGhVeHD8u9T+quv6uJzX2N98YfEokAlBXKIgUIjrdYEe45+gpnjv4yfOCLbwVFdxn7Td/tOvhpBGGxeZWNtmSJEoEBVCETaYxOIa7zuUzXGAsR8oGKkLCXLTbtRy+tZ5Y5NWSla7m5ygsYRqye/oWef/ysGG5fxzqM+hThA8wKNsHvvMfY89ps093xU8C3QUAbPTdty332jrvkmvc1VUAixAPXECM3xedKxORt7GAsQ80HPEnmP+9Cx3BTsHKPORT374//M0plvo8UA71NCjJD3yfM+9dYM++//FLsf+jWS8UPlJNWbHAZ8t5+JAsVwk1F/ixAjHinL3ksgaY1D2n6vPzhjLEDMB5XuFGx0wOqFH+iZH/xv9JbP4lMB7xnFSBgN0RiZ23Ocw0/+AWP7PiG4hJ37R15bguQWfF0goCM2Vy4xGPaJEcCV26C9Z2xsgrJib/nfG2MBYsydjI9qS3Aselz8yX/RS89+mZBvkGQ1QgwQIPS2kKzFkSd+mX1PfJGktVe2G/nbvvMp5PTWrzIcjICUGCMxKmktoTU1D66+PVyxH6axADHmTo08tm85LLqX9MyP/xNLJ78HorikQYgjQgGjXp/W1G7u++Qfseu+zwuSVlfr3plef8y3GHRXyfOAT9Ly646RWi0jbU6CJFZE0ViAGHMnw2N72qq7/IKe/8GfsrX8KrWsRh5GRI2QR0IxYvexj3Dfx/6IxtyDO2sdd6TybzWDNehc1Y315XL7bgTBkVPQbN2wA8uyw1iAGHPHxh6IODYXv6fnfvRnDDpXSdKMUES8Swl5n7RW48gTv8Oux35L0sb09VHHHS4bH/sb9NeW0OqYuQAaAq2JKRoTB2wHlrEAMeYONcdQ1s9l+eQ/6MWn/5yQb+KShCKUARHyAY3WLg4/+btMHf2Fasqq2p77HjTVxXCNMNwq7xoRhziPl4T62Dgum7IKWMYCxJjbPurQWN7bEUdceParunjiK2SMEJ8QiohSUAxHtGaPceRjf8jY/JMSEZzG8jT6nVataWysXmI4ynGSIM6VlXidpz0+Q3SZ7b0yFiDG3Ob4KEcQYciZH/7vevHZr5KlSuE8Qnm3RhjlTO99lIMf+/c0po5IfN1p8jv/NasW5J01RnmB9ynelYcdfeKZnN2Lq41VU1g2iWUsQIy5HUMPECEWA059/0/10omvkSWRQlLQAgYRJ559D36Bhce/JGlrF2h5G/ktPxj4Nr/mordKb30RNOI9eAchKvV6naQ2DqTAnawPZowFiPkAhUcUQYo+p7//Z3rxJ1+l6T1RHBIjYTRCg2P/x7/EgQ/9ruCbXL+X/L0dMYGQb63q2vIiEj0krizrokqrPUXa2lX9Xht9GAsQY259IyyChAGnf/CnevmFr1HPIkX0qAbiYESQGvd94g/Y++Hfkygp7i45T7G9MB6Gm/S2NokKTpQonqCRWmuc5vQhu//DWIAYc+sHHuXdGDGOOP/0n+ulE39N6pQQEwKBYjAg8S0e+PQfs/Dwbwh4pFpkvxtItbeqv36ZvN8ta2KplPUmnTI2PoX69vUilHaI0FiAGHMrRCKCF2X5xb/TK89/lRqRIjok5miR432T+z7zxyw89JtSrh/oXRMe5QikXBbfWl0kHwzx3pe3OFYZNzG7gK+3RVEbgph7gq3SmXtk+CF4ETrnv62LJ76Ckxxx1U2HISe6Fsc++W9ZeOg3RLW8j+Rua4UFRxz1GXSuEWLAeYcXQQSSrE4yNgVps5rrsgQxFiDGvMteewANIELv2nN68Zm/pBh2cEm9KpLrcGmd4x//PfY++puC+mrm5y5rgDUCMNpa1vWl84BH3PYZEGF8fIL25CFUq3tH7CShuQfYFJa5+4kndq9w8Zm/pLt+CXDEoiAoROc5+thvsfDE74i6pLxb/S7uvetoncHWKk483nnEKaKRsXabsekDOzuybP3D2AjEmHfV2irg0aLH4vN/oeuXT6BRKYqcUVHQGwyYP/IJ5h/7LVFXr3r5d2vDW35dWxuXiKMuWZLineAkIXWOyakZYjpuP3NjIxBjblGCoAjrZ76hy2e/j4gnxoAqhNGQ2b2PceDDf4BkE1Wv/e7tD21vzR10rjEajkjTFHFS/W+e8ekFkta03UJoLECMuSWjD3EMV17Ray/8DUU+rGZ2hBhyxib3ct8n/i3Z+IHr25ju4iAUhDDsMlo7h4jiM0eSOGIEX2uSTexFJbPsMBYgxrzbBhcRQt7j0jN/wdrSaYQMFSHGgE/qHPjIH9Dc/ZCU5djdXf/tIKD5hvZWziIa8UmGEwdOaU60GN99DCSr/gWLEXNvsDUQcxcOPsotSOtnv6lXz/2IWETCqCAOh4wGOQsPfp5dxz4n99pac95bZTjYrO4tuZ4uU+MT+MZMuYBu26+MBYgx7zg9EHEMNs/p5Z/8DfmgCwFihH6/R3v+AfY99luiLuFeKzi4tbHIVmcTkQRVIeKIKjQnZnH1KYsOc8+xKSxzd+QGVFtwQcOI5Rf/mpWrryJalvsYhi3SsVnu+9gf4lvzVYkSuTe+MxE0RvLOZfLREPEp6j0gJLWE+tguJB23S6SMjUCMeacNrVah0L36gl45+RQSFCdQEIhROfDoLzJx8KOiO4vmd//jq9UBQvIO65deZlTkBBwFkGtOUk9ozhxEpY5twTI2AjHmHRBVVDxadLny6t/RWb8KCBElH42YmD/Ovke+iCJVdd17q4+WD1Z1q3OVYhRwmYMiAkqjMUY6tg/xqR0gNDYCMeadjT/KTOhde0HXzj0NMSIqhDyAb3Lwid8kHd8jaAB37zy229NyvY3LdNdWcM4BRXkPOjA2MYNvzRN3PgVjLECMeXvxIY5YDFg+9U2K3ibiElQDRZEzu+8+Zo98qqpw5e+tb03KXWX9lfPkgy4+8SSJ4LySpEq9PYdk4zbuMBYgxrzj4QcwXH1ZN6+cIOLwzhOiUKuNc+iJ3yKpT92DUzwKOLTos3rlRWKIpGmG8x4vkVrWYGL3A5BUJUwsRowFiDFvt5cuSByxeflHbG11EFdDfIInMHfkcdr7n7w315erYBz113TUvYYT8F5InCAkjE9M0pg6Aq5a/7AFdGMBYszbaWTLVjZ0l3Tj0vMMRzkgRFWy5hgLxz9Jko3f5YUSf7qiu0ivcw1x1c4xVcQFGhOTJGO7EIsOYwFizDsZfYAS2Vp6nv7aZVCIBGI+YmL+GGPzj97cnb/HRlagbC29iOZ9XNZAkhTnU5LUMTF7BMmsgKK5d9k2XvNeDj9QhJBvsXHlOXrdIaJKDJHEBeYOPE46tle2y7rfa98bCJr3GGxcQKOnVisr8MYgNJp1xmaO4LKJ60lqjAWIMW+1jdWyum5nUTeXLjLM83LxPATa0/O05x+uGla9N9c/BEJvWQedJVyipIlDnEe9MDUzRXPmyM2/2RgLEGPeomrX0dbVF+iuXy3b0cKhccj03oepz9x/707vVLfSbq28RN69hnMeceURFkEYn96P1HfbM2AsQIx5J110BWLRp7tymn6nQ1QIcUCawvj8cSRpVJNcck9+b8SC4do5hr0+aZIhHlQSsppQm5rH1Wds2GHuabaIbt6rNhZBiP1l3Vw6QyiGoAV53qXZnqM5c6zsyOu9+73pYJmt9UWCOHySkCQJzjkarQnqk0eq+z9s+spYgBjzjvRXz9LfWCEWghaCRGVy7hDZxKF7tjptNf5gsHZKe+sXwXtEEsDhnNIe303SOLizS8sYCxBj3o5q/aO3dpaNtWuEAoqRIi5lYtdhXNZiuxT6vfi9aYz0lk4y7G3gJUGkPMeSJEpzaj/SnJcI5WXpxliAGPPW++gAMe/TX7vEsD9iFJX+aEhaHydp7y3bYb0356+2p682ll6iKAq8AycKKLWsTm1iP7g67l7cXWaMBYi5C/KDmPfZXL5IPiwogjIKObX2JGNzR+/diR3d3n11Ursr5xD15Sl6cag4WpPz+PFDqEh1ut4YCxBj3rbQ39Bhv88wRGIsEIk0J6aRbEJuyJl7iwiosrX0MqP+BuIdiiNIQpoKYzOH8c295cScOGwIYixAjHkHemuLdDqr5CTEqDiFiZl9+No4gt6Dyx/V1NxghfVrr6IKzkt5B4gGarUGtan7wDew3VfGAsSYd9TMlg3taLhMb2sNiZFQ5CCQ1CcQn6Gq99gIRNFqzaaz9Ip2lk/jfR3nk/IQIZFmezfpxFHbd2UsQIx553306qaMogejAieK04iv14i+DpTnKOReezxFUC3YvPI8oejj0wxxHhGHS4TWrqNIfU7K/ck2+jAWIMa87QgpwyGSD7vEOMQpaFQazSZj7bmqMb7Hvistv698/bx2Lj+H8x7xNVziUBdotiZpzj6EuAywxXNjAWLMO++pFwWjQYcQCpBIJJBmdZrtmXvzW6rGVt1rJxhuXSNLazgf8d7jXaQ9vYdk4r7qcKSNPsz7g9XCMne2oa3WjmMMDPtdoiqKoqI4nyJJfXugcg+1s+Wd7sVwg40rz5VrOVmGiIAKPm3Q2PUgkk3uBKgxFiDGvGOBEIfEGIgxQTWAB/X34COpZSj0lk9od/Ukab1JkqSIJGgc0ZraR3PXh7kHk9EYCxBz97W3SHVkIpa/YohoFETusYujVEGUOBqwtvgjVAuyehtX3XsuktCaPYJvLlSDLwsPYwFizLvprpdNqbhySkuVGMvpnnvtdHY5AecYrL2kW1dOkGRNnPMg5feXNscY2/VRcFm1TmIBYt4/bBHdvGc9d+fc9TMR4srDg0VxT8WHiEAYsHLhX9BiiySpIRJJfELihdbkXvz4ftmpcWKMBYgx71DVARdxpEkDEYgoqKCxIITBTb/vrh9MIQzWzujapRdJak28gDhB0kiapYzv+jCStonbc3bGWIAY8+4SRJKMrDEOODRGRJUwGjLoLd874w8RCDnXTv5XpBiRpjVASVwGhVAfP0Q282C19mFnP4wFiDHvstNeFhsUSai1JnAuRUPEoQy2uvQ2l27o3d/N34giQOfqj7Rz+UWarSbiHN55nBd8ljI2/yQkEziNtvJhLECMuVUxAoCvIYkSYrkY3ettQdGrfoeihLvyK1cNqJT3uV968e9w5LjEgRY479BY0Jo4RDb9YFW1ROxVMxYgxtxSfoJavU0kgBOKUU6+tYoWg2pR/e7rt0v12gjC6tlv69bSKySNjCLEsgCkRgRPe9+nkbRdXYpl4w9jAWLMLW2G21MHGJ/YTUSRxCNRWV86TzHcRCiPWNx9Q5CIiJB3r3DpJ1+hUU9IfIKPivMJed6nMfcY2dSDorZt11iAGHNro2O7SU1a05I0xnEqRBXyGNncWCXvL93lKyDKpRNf0TC8Qr3ZQqIgSYpoRNI2E3t/HiQtRx9ie3eNBYgxt3oAgmRjzMztJ0shFI4ipqxdu0p36dRdmhtlzauNC9/V5dPfoD0+VZbBEgXvGPRHTO7/LNnUESl/r40+jAWIMbc8QRRwaZP2zAKNZgooOEe/s05/+Qyqxd3VAGsEEUa9Jc7++H+nUXdkrobg8IlHhn2SsQNMHvhUtXCurxlvGWMBYsytiZBqgaM+fZD2xG6cKPXU4UVYu/Qy+dY1pdryexekR3kQUAvO//jPVAfXaLcnwQmSJDhRBgXMH/8Cvj5Ned+HvVrGAsSY26q9+0Gmdx+g2YBm3ZEmnvVrp9m6/Pxd03dXBSfCxRNf1o1z32R6erIcRfmENE3Z7PQZ2/tpWns+JFHtwKCxADHmNg9ByrMevjUruw8cZryVkmUJjXpG3uuysfhjtOhX01jv3ShENSAiLJ/6ji4+82dMz06Q+AwcJIkw6nXJxvaz58FfF8Tj0HvvKl5jLEDMvZYgguJ8nfH5R2hP7EIEMu9AA0tnn6Z37SUtG3F9D0JEq/DwbF56Wk//6H9ibm6SerMFTkgShwsDRrHBvsf/EFefLr/Ge60cvTEWIOaepNV5kIXHGN+9H0eBCohP6axeYen018tDhQh3+h5xVUXEM1h6VU99739kdiKhPTaHSIZL63ifsbU1YveDv0p95gFBA7ZgbixAjLlzg5DyIRzbI3MHHqHRqiMC4hJChEuvfIvu4nMqInfumhClLO4ojv7SSX3xW/8DY41Ia3yOnAJJ6iRZnc7mFq19n2Hi0Odke3uvMRYgxtzJBFFFXMrU0c8xvesAUcvNV96l9NdXOf/sn1H0VhDn78AoRMv9Vs7RufqSnvj6/8BYvcvk7BxRwbmMNE0ZbKxSn7if3Q/9jiBJFYQ2+jAWIMbc4QwpG9508rjM3vdZXD1DcQQgD8rFkz/k9A/+VDUMy8f1Nm3r1apmlYhj+fR39IV//r8z0dxiYnKOfBSJ4kjTGoPOMrG2m4UP/ytxWRu749xYgBjzXlJFXML08V9gduEYIR9QFMpIYTRSTv7oa5x7+j8rBFQEjfEWrakraCRWO62IBWef/nN98ev/gemxwNj4GHk+RDUnSx29zSUCc+x78t8j9TmIFh7mg83uRDd3xShEVcnGj8i+x39HV5cv0NvcxPkWTnJc3uelb/9PaDHSQ0/+oZDWy0XunXIhb78RV43l2EEcDthaPa0nn/qPdK78gP0LM6SNcfI84r2QpEpv9RIhWeDAx/890twj5SK7/ejMB/zVVbVib+ZuGIVEooALOWd+8D/qK9/9C4QEEap7QQJojX0PfJpDH/19mrP3SzWGqE61v7b2lLxmpLE9aFHkhgXvUe8aV176Z118+R+puR67ZtsIDRTFJYr3GWsbqyRjxznysT8R15irLsSy9DDGAsTcVSGCOPLeVU594z/oxRe/jfM1VAQnnsQrIeQ0xhfYffwXmTv+C9Sn94h73UD6xqmlN5pmUrbWLumVV77F8vmv48MmU1MT1OttYiyDLPHgNWd9bYts95Mc/PAfis+my/s+bMeVMRYg5m5U1pHKOxf15Df/A1dO/YgkycDV8ALeC8TIMIxIGjNM7n2C2QMfpjVzmKw1JUnWRFx6PSo0EsOIYrRFv7OqneUzbCw+w8bln5DRYXJ6ikZ7EiQpd+MmKUkKo96AbmfE7LFfZO7B3yx3W1U7xGzdwxgLEHO3DkRQBCHvnNfT3/ufWT77FN5nOBJERqgv7w/RUSAfDYhSQ9IW2dgsE9N7SbI2Kh7VAo2BUW+NzvpFXOjiwoBa09EYa1Or1RESEEeS1JFaRuqUrc0uQzfLwoO/zsTej1Q3eoSyRImK5YcxFiDmbo8REIqty3rl+T/n8qlvE4ohqUspVFFVPAnRhfKWwLBzsB1FwDm8OLxzOC8kCdQyV9ax8inReTQqNS9IluIUBr0u/TxjYs/HmX/kVyVp7K7CzEYdxliAmHssQyIqDmKPjdPf0MWX/oHNaycRIt43Ca7chuucx7m0rE/lPU4EfIoT8OJxTndKVAngxZF4h4gSipx+r0vuajSmH2fu2OdoLzxa3uZRrckYYyxAzD04ClEU1CECRfcKa2e+rdfOfI+N5VM4AklSQ9IU8RniIPEO5zziE5xzeCeI0zJIpKyVq8WQUPTpD3LwU7TnH2T6yM8zvvtBAcfOOyFi4w5jLEDM+yFItsukF1tLrF16VjuXn6O7dJLhYA3nFI3ls+wQnBNwHnEO7zxp4lAi/RzqY3uoT+yjves+2nMPURvfcz0n7CpaYyxAzPsvRNBqRWJ7ZKAFg85FLbor9DavkHdXytFFGJWn1cWBc+BrpI0p2lPzuGycbHy3ZI3ZGzIjItWfa4yxADHvWxGtDgWKCG88ybR9f8ibn1K/8Y4REbu73BgLEPMBHJjoTbHx2nWLcjH8xlChDAsbbRhjAWKMMea9YXsUjTHGWIAYY4yxADHGGGMBYowxxgLEGGOMsQAxxhhjAWKMMcYCxBhjjAWIMcYYCxBjjDHGAsQYY4wFiDHGGAsQY4wxFiDGGGMsQIwxxhgLEGOMMRYgxhhjLECMMcZYgBhjjLEAMcYYYyxAjDHGWIAYY4yxADHGGGMBYowxxgLEGGOMsQAxxhhjAWKMMcYCxBhjjAWIMcYYCxBjjDHGAsQYY4wFiDHGGAsQY4wxFiDGGGMsQIwxxhgLEGOMMRYgxhhjLECMMcZYgBhjjDEWIMYYYyxAjDHGWIAYY4yxADHGGGMBYowxxliAGGOMsQAxxhhjAWKMMcYCxBhjjAWIMcYYYwFijDHGAsQYY4wFiDHGGAsQY4wxFiDGGGOMBYgxxhgLEGOMMRYgxhhjLECMMcZYgBhjjDEWIMYYYyxAjDHGWIAYY4yxADHGGGMBYowxxliAGGOMsQAxxhhjAWKMMcYCxBhjjAWIMcYYYwFijDHGAsQYY4wFiDHGGAsQY4wxFiD2ERhjjLEAMcYYYwFijDHGAsQYY4wFiDHGGGMBYowxxgLEGGOMBYgxxhgLEGOMMRYgxhhjjAWIMcYYCxBjjDEWIMYYYyxAjDHGWIAYY4wxFiDGGGMsQIwxxliAGGOMsQAxxhhjAWKMMcZYgBhjjLEAMcYYYwFijDHGAsQYY4wFiDHGGGMBYowx5jb5/wM9MxR4QzpHeQAAAABJRU5ErkJggg==";

const PROCEDIMENTOS_LIST = ["Preenchimento labial","Preenchimento mento","Preenchimento malar","Preenchimento mandíbula","Preenchimento bigode chinês","Preenchimento linha de marionete","Botox","Clareamento","Profilaxia","Raspagem","Restauração","Extração simples","Extração elemento impactado","Prótese","Placa bruxismo","Sousmile","Avaliação","Retorno"];
const MEIOS_PAGAMENTO = ["Pix","Débito","Crédito","TED","Contrato Pix (parcela)","Dinheiro"];
const MEIOS_CONTATO = ["Instagram","WhatsApp","TikTok","Indicação","Outro"];

function uid() { return Math.random().toString(36).slice(2,10); }
function fmt(n) { return (n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}); }
function fmtDate(d) { if(!d) return "—"; const [y,m,day]=d.split("-"); return `${day}/${m}/${y}`; }
function age(dob) { if(!dob) return ""; const b=new Date(dob),now=new Date(); let a=now.getFullYear()-b.getFullYear(); if(now<new Date(now.getFullYear(),b.getMonth(),b.getDate())) a--; return a+" anos"; }

const gs = {
  app: { display:"flex", height:"100vh", fontFamily:"'Inter', -apple-system, sans-serif", background:C.cream, color:C.text, overflow:"hidden" },
  sidebar: { width:240, background:C.wineDark, display:"flex", flexDirection:"column", padding:"0 0 24px", flexShrink:0 },
  logo: { padding:"28px 24px 20px", borderBottom:`1px solid rgba(255,255,255,0.08)` },
  logoTitle: { fontFamily:"'Playfair Display', Georgia, serif", fontSize:16, color:C.white, letterSpacing:2, fontWeight:600, textTransform:'uppercase' },
  logoSub: { fontSize:11, color:C.goldLight, letterSpacing:2, marginTop:4, fontWeight:400 },
  navItem: (active) => ({ display:"flex", alignItems:"center", gap:12, padding:"11px 24px", cursor:"pointer", color: active ? C.goldLight : "rgba(255,255,255,0.6)", background: active ? "rgba(201,168,76,0.12)" : "transparent", borderLeft: active ? `3px solid ${C.gold}` : "3px solid transparent", fontSize:14, letterSpacing:0.5, transition:"all .18s" }),
  navLabel: { fontSize:11, color:"rgba(255,255,255,0.25)", padding:"18px 24px 8px", letterSpacing:2, textTransform:"uppercase", fontFamily:"'Playfair Display', Georgia, serif" },
  main: { flex:1, display:"flex", flexDirection:"column", overflow:"hidden" },
  topbar: { background:C.white, borderBottom:`1px solid ${C.sand}`, padding:"16px 32px", display:"flex", alignItems:"center", justifyContent:"space-between", flexShrink:0 },
  content: { flex:1, overflowY:"auto", padding:"32px" },
  card: { background:C.white, borderRadius:16, border:`1px solid ${C.sand}`, padding:"28px", marginBottom:20 },
  cardTitle: { fontSize:20, fontWeight:600, color:C.wine, fontFamily:"'Playfair Display', Georgia, serif", letterSpacing:2, marginBottom:4, textTransform:'uppercase' },
  grid2: { display:"grid", gridTemplateColumns:"1fr 1fr", gap:20 },
  grid4: { display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:16 },
  label: { display:"block", fontSize:12, letterSpacing:1.5, color:C.textMuted, marginBottom:6, textTransform:"uppercase", fontFamily:"'Playfair Display', Georgia, serif", fontWeight:500 },
  input: { width:"100%", padding:"12px 16px", border:`1px solid ${C.sandDark}`, borderRadius:10, fontSize:15, background:C.cream, color:C.text, fontFamily:"'Inter', -apple-system, sans-serif", outline:"none", boxSizing:"border-box" },
  textarea: { width:"100%", padding:"12px 16px", border:`1px solid ${C.sandDark}`, borderRadius:10, fontSize:15, background:C.cream, color:C.text, fontFamily:"'Inter', -apple-system, sans-serif", outline:"none", resize:"vertical", minHeight:90, boxSizing:"border-box" },
  select: { width:"100%", padding:"12px 16px", border:`1px solid ${C.sandDark}`, borderRadius:10, fontSize:15, background:C.cream, color:C.text, fontFamily:"'Inter', -apple-system, sans-serif", outline:"none", cursor:"pointer", boxSizing:"border-box" },
  btn: { padding:"12px 28px", background:C.wine, color:C.white, border:"none", borderRadius:10, fontSize:14, cursor:"pointer", fontFamily:"'Inter', -apple-system, sans-serif", letterSpacing:1, fontWeight:600 },
  btnOutline: { padding:"10px 22px", background:"transparent", color:C.wine, border:`1.5px solid ${C.wine}`, borderRadius:10, fontSize:14, cursor:"pointer", fontFamily:"'Inter', -apple-system, sans-serif", letterSpacing:1 },
  statCard: { background:C.white, borderRadius:14, border:`1px solid ${C.sand}`, padding:"24px", textAlign:"center" },
  statNum: { fontSize:32, fontWeight:600, color:C.wine, fontFamily:"'Inter', -apple-system, sans-serif" },
  statLabel: { fontSize:12, color:C.textMuted, letterSpacing:1.5, textTransform:"uppercase", marginTop:6, fontFamily:"'Playfair Display', Georgia, serif" },
  tag: (color) => ({ display:"inline-block", padding:"3px 10px", borderRadius:20, fontSize:12, background: color==="gold"?C.goldAlpha:C.wineAlpha, color: color==="gold"?C.wine:C.wineLight, border:`1px solid ${color==="gold"?C.goldLight:C.wineLight}`, marginRight:4, marginBottom:4 }),
  table: { width:"100%", borderCollapse:"collapse" },
  th: { padding:"12px 16px", textAlign:"left", fontSize:11, color:C.textMuted, letterSpacing:1, textTransform:"uppercase", borderBottom:`1px solid ${C.sand}`, fontWeight:500 },
  td: { padding:"14px 16px", fontSize:14, borderBottom:`1px solid ${C.ivory}`, verticalAlign:"top" },
  badge: { padding:"3px 10px", borderRadius:20, fontSize:12, background:C.successBg, color:C.success, fontWeight:500 },
};

function Checklist({ options, value=[], onChange, columns=2 }) {
  return (
    <div style={{ display:"grid", gridTemplateColumns:`repeat(${columns},1fr)`, gap:"8px 16px" }}>
      {options.map(opt => {
        const checked = value.includes(opt);
        return (
          <label key={opt} style={{ display:"flex", alignItems:"center", gap:8, cursor:"pointer", fontSize:14, color: checked?C.wine:C.textMuted, userSelect:"none" }}>
            <input type="checkbox" checked={checked} onChange={() => { if(checked) onChange(value.filter(x=>x!==opt)); else onChange([...value, opt]); }} style={{ accentColor:C.wine, width:16, height:16, cursor:"pointer", flexShrink:0 }} />
            <span>{opt}</span>
          </label>
        );
      })}
    </div>
  );
}

function Field({ label, children, span=1 }) {
  return (
    <div style={{ gridColumn:`span ${span}` }}>
      <label style={gs.label}>{label}</label>
      {children}
    </div>
  );
}

function Modal({ title, onClose, children, wide=false }) {
  return (
    <div style={{ position:"fixed", inset:0, background:"rgba(44,31,37,0.55)", zIndex:1000, display:"flex", alignItems:"flex-start", justifyContent:"center", padding:"40px 20px", overflowY:"auto" }}>
      <div style={{ background:C.white, borderRadius:20, width:"100%", maxWidth: wide?900:680, boxShadow:"0 24px 80px rgba(107,45,62,0.25)" }}>
        <div style={{ padding:"24px 32px", borderBottom:`1px solid ${C.sand}`, display:"flex", alignItems:"center", justifyContent:"space-between" }}>
          <h2 style={{ margin:0, fontSize:22, fontFamily:"'Inter', -apple-system, sans-serif", color:C.wine, fontWeight:500 }}>{title}</h2>
          <button onClick={onClose} style={{ background:"none", border:"none", fontSize:22, cursor:"pointer", color:C.textMuted }}>✕</button>
        </div>
        <div style={{ padding:"32px" }}>{children}</div>
      </div>
    </div>
  );
}

function SearchBar({ value, onChange, placeholder }) {
  return (
    <div style={{ position:"relative", maxWidth:340 }}>
      <span style={{ position:"absolute", left:14, top:"50%", transform:"translateY(-50%)", color:C.textMuted }}>🔍</span>
      <input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder||"Buscar..."} style={{ ...gs.input, paddingLeft:42 }} />
    </div>
  );
}

function LoadingScreen() {
  return (
    <div style={{ display:"flex", alignItems:"center", justifyContent:"center", height:"100vh", background:C.cream, flexDirection:"column", gap:16 }}>
      <div style={{ width:48, height:48, border:`3px solid ${C.sand}`, borderTop:`3px solid ${C.wine}`, borderRadius:"50%", animation:"spin 1s linear infinite" }} />
      <p style={{ color:C.textMuted, fontFamily:"'Inter', sans-serif", letterSpacing:2, fontSize:14 }}>CARREGANDO</p>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}

// ── DASHBOARD ─────────────────────────────────────────────────────────────────
function Dashboard({ patients, consultas, pagamentos, leads, onNav }) {
  const totalReceita = pagamentos.reduce((s,p)=>s+(p.valor_pago||0),0);
  const totalLucro = pagamentos.reduce((s,p)=>s+((p.valor_pago||0)-(p.insumos||0)-(p.aluguel||0)),0);
  const procedCount = {};
  consultas.forEach(c=>(c.procedimentos||[]).forEach(p=>{ procedCount[p]=(procedCount[p]||0)+1; }));
  const topProcs = Object.entries(procedCount).sort((a,b)=>b[1]-a[1]).slice(0,5);
  const recentConsultas = [...consultas].sort((a,b)=>(b.data||"").localeCompare(a.data||"")).slice(0,5);

  return (
    <div>
      <div style={{ marginBottom:32 }}>
        <h1 style={{ fontSize:28, fontFamily:"'Playfair Display', serif", color:C.wine, fontWeight:600, marginBottom:6, textTransform:"uppercase", letterSpacing:2 }}>Visão Geral</h1>
        <p style={{ color:C.textMuted, fontSize:15 }}>{new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"})}</p>
      </div>
      <div style={gs.grid4}>
        {[{n:patients.length,l:"Pacientes"},{n:consultas.length,l:"Consultas"},{n:leads.length,l:"Leads"},{n:fmt(totalReceita),l:"Receita Total"}].map(s=>(
          <div key={s.l} style={gs.statCard}>
            <div style={gs.statNum}>{s.n}</div>
            <div style={gs.statLabel}>{s.l}</div>
          </div>
        ))}
      </div>
      <div style={{ ...gs.grid2, marginTop:20 }}>
        <div style={gs.card}>
          <div style={gs.cardTitle}>Financeiro</div>
          <div style={{ display:"flex", gap:24, marginTop:12 }}>
            <div><div style={{ fontSize:11, color:C.textMuted, letterSpacing:1, textTransform:"uppercase" }}>Receita</div><div style={{ fontSize:24, color:C.wine, fontFamily:"'Inter', sans-serif", fontWeight:600 }}>{fmt(totalReceita)}</div></div>
            <div><div style={{ fontSize:11, color:C.textMuted, letterSpacing:1, textTransform:"uppercase" }}>Lucro</div><div style={{ fontSize:24, color:C.success, fontFamily:"'Inter', sans-serif", fontWeight:600 }}>{fmt(totalLucro)}</div></div>
          </div>
        </div>
        <div style={gs.card}>
          <div style={gs.cardTitle}>Procedimentos em Alta</div>
          <div style={{ marginTop:12 }}>
            {topProcs.map(([proc,count],i)=>(
              <div key={proc} style={{ display:"flex", alignItems:"center", gap:12, marginBottom:12 }}>
                <div style={{ width:24, height:24, borderRadius:6, background:C.wineAlpha, display:"flex", alignItems:"center", justifyContent:"center", fontSize:12, color:C.wine, fontWeight:600, flexShrink:0 }}>{i+1}</div>
                <div style={{ flex:1, fontSize:14 }}>{proc}</div>
                <div style={{ fontSize:13, color:C.textMuted }}>{count}x</div>
              </div>
            ))}
            {topProcs.length===0 && <p style={{ color:C.textMuted, fontSize:14 }}>Nenhum procedimento ainda.</p>}
          </div>
        </div>
      </div>
      <div style={gs.card}>
        <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:20 }}>
          <div style={gs.cardTitle}>Consultas Recentes</div>
          <button onClick={()=>onNav("consultas")} style={gs.btnOutline}>Ver todas</button>
        </div>
        <table style={gs.table}>
          <thead><tr>{["Registro","Paciente","Data","Procedimentos"].map(h=><th key={h} style={gs.th}>{h}</th>)}</tr></thead>
          <tbody>
            {recentConsultas.map(c=>{
              const pac = patients.find(p=>p.id===c.paciente_id);
              return (
                <tr key={c.id}>
                  <td style={gs.td}><span style={gs.badge}>{c.registro}</span></td>
                  <td style={{ ...gs.td, fontWeight:500 }}>{pac?.nome||"—"}</td>
                  <td style={{ ...gs.td, color:C.textMuted }}>{fmtDate(c.data)}</td>
                  <td style={gs.td}>{(c.procedimentos||[]).slice(0,2).map(p=><span key={p} style={gs.tag()}>{p}</span>)}</td>
                </tr>
              );
            })}
            {recentConsultas.length===0 && <tr><td colSpan={4} style={{ padding:"24px", textAlign:"center", color:C.textMuted }}>Nenhuma consulta ainda.</td></tr>}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ── PATIENT FORM ───────────────────────────────────────────────────────────────
function PatientForm({ initial={}, onSave, onClose }) {
  const [f,setF] = useState({ nome:"",nascimento:"",primeira_consulta:"",sexo:"Feminino",estado_civil:"Solteiro(a)",endereco:"",celular:"",rg:"",cpf:"",profissao:"",altura:"",peso:"",contato_emergencia:"",ultima_consulta_medica:"",ultima_consulta_odonto:"",historico_medico:"",alergias:"",medicamentos:"",queixa_principal:"",observacoes:"", ...initial });
  const set = k => e => setF(p=>({...p,[k]:e.target.value}));
  return (
    <div>
      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:20 }}>
        <Field label="Nome Completo" span={2}><input style={gs.input} value={f.nome} onChange={set("nome")} /></Field>
        <Field label="Data de Nascimento"><input type="date" style={gs.input} value={f.nascimento} onChange={set("nascimento")} /></Field>
        <Field label="Primeira Consulta"><input type="date" style={gs.input} value={f.primeira_consulta} onChange={set("primeira_consulta")} /></Field>
        <Field label="Sexo"><select style={gs.select} value={f.sexo} onChange={set("sexo")}><option>Feminino</option><option>Masculino</option><option>Outro</option></select></Field>
        <Field label="Estado Civil"><select style={gs.select} value={f.estado_civil} onChange={set("estado_civil")}><option>Solteiro(a)</option><option>Casado(a)</option><option>Divorciado(a)</option><option>Viúvo(a)</option></select></Field>
        <Field label="Endereço" span={2}><input style={gs.input} value={f.endereco} onChange={set("endereco")} /></Field>
        <Field label="Celular"><input style={gs.input} value={f.celular} onChange={set("celular")} /></Field>
        <Field label="Profissão"><input style={gs.input} value={f.profissao} onChange={set("profissao")} /></Field>
        <Field label="RG"><input style={gs.input} value={f.rg} onChange={set("rg")} /></Field>
        <Field label="CPF"><input style={gs.input} value={f.cpf} onChange={set("cpf")} /></Field>
        <Field label="Altura"><input style={gs.input} value={f.altura} onChange={set("altura")} /></Field>
        <Field label="Peso"><input style={gs.input} value={f.peso} onChange={set("peso")} /></Field>
        <Field label="Contato de Emergência" span={2}><input style={gs.input} value={f.contato_emergencia} onChange={set("contato_emergencia")} /></Field>
        <Field label="Última Consulta Médica"><input style={gs.input} value={f.ultima_consulta_medica} onChange={set("ultima_consulta_medica")} /></Field>
        <Field label="Última Consulta Odontológica"><input style={gs.input} value={f.ultima_consulta_odonto} onChange={set("ultima_consulta_odonto")} /></Field>
        <Field label="Histórico Médico" span={2}><textarea style={gs.textarea} value={f.historico_medico} onChange={set("historico_medico")} /></Field>
        <Field label="Alergias" span={2}><textarea style={gs.textarea} value={f.alergias} onChange={set("alergias")} /></Field>
        <Field label="Medicamentos em Uso" span={2}><textarea style={gs.textarea} value={f.medicamentos} onChange={set("medicamentos")} /></Field>
        <Field label="Queixa Principal" span={2}><textarea style={gs.textarea} value={f.queixa_principal} onChange={set("queixa_principal")} /></Field>
        <Field label="Observações" span={2}><textarea style={gs.textarea} value={f.observacoes} onChange={set("observacoes")} /></Field>
      </div>
      <div style={{ display:"flex", gap:12, justifyContent:"flex-end", marginTop:28, borderTop:`1px solid ${C.sand}`, paddingTop:24 }}>
        <button style={gs.btnOutline} onClick={onClose}>Cancelar</button>
        <button style={gs.btn} onClick={()=>onSave(f)}>Salvar Paciente</button>
      </div>
    </div>
  );
}

function PatientsPage({ patients, consultas, pagamentos, setPatients }) {
  const [search,setSearch]=useState("");
  const [modal,setModal]=useState(null);
  const [view,setView]=useState(null);
  const [saving,setSaving]=useState(false);

  const filtered = patients.filter(p=>
    p.nome?.toLowerCase().includes(search.toLowerCase())||
    p.celular?.includes(search)||p.cpf?.includes(search)
  );

  const save = async (data) => {
    setSaving(true);
    try {
      if(modal==="new") {
        const { data: row, error } = await supabase.from("pacientes").insert([data]).select().single();
        if(!error) setPatients(p=>[...p, row]);
      } else {
        const { error } = await supabase.from("pacientes").update(data).eq("id", modal.id);
        if(!error) setPatients(p=>p.map(x=>x.id===modal.id?{...x,...data}:x));
      }
    } finally { setSaving(false); setModal(null); }
  };

  if(view) return <PatientDetail patient={view} consultas={consultas} pagamentos={pagamentos} onBack={()=>setView(null)} onEdit={p=>{setModal(p);setView(null);}} />;

  return (
    <div>
      <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:28 }}>
        <div>
          <h1 style={{ fontSize:26, fontFamily:"'Inter', sans-serif", color:C.wine, fontWeight:400, marginBottom:4 }}>Pacientes</h1>
          <p style={{ color:C.textMuted, fontSize:14 }}>{patients.length} pacientes cadastrados</p>
        </div>
        <button style={gs.btn} onClick={()=>setModal("new")}>+ Novo Paciente</button>
      </div>
      <div style={{ ...gs.card, marginBottom:20 }}><SearchBar value={search} onChange={setSearch} placeholder="Buscar por nome, celular ou CPF..." /></div>
      <div style={gs.card}>
        <table style={gs.table}>
          <thead><tr>{["Paciente","Celular","Nascimento","Primeira Consulta",""].map(h=><th key={h} style={gs.th}>{h}</th>)}</tr></thead>
          <tbody>
            {filtered.map(p=>(
              <tr key={p.id} style={{ cursor:"pointer" }} onClick={()=>setView(p)}>
                <td style={gs.td}>
                  <div style={{ display:"flex", alignItems:"center", gap:12 }}>
                    <div style={{ width:36, height:36, borderRadius:"50%", background:C.wineAlpha, display:"flex", alignItems:"center", justifyContent:"center", color:C.wine, fontSize:14, fontWeight:600, flexShrink:0 }}>{p.nome?.split(" ").map(n=>n[0]).slice(0,2).join("")}</div>
                    <div><div style={{ fontWeight:600, fontSize:15 }}>{p.nome}</div><div style={{ fontSize:12, color:C.textMuted }}>{p.profissao}</div></div>
                  </div>
                </td>
                <td style={{ ...gs.td, color:C.textMuted }}>{p.celular}</td>
                <td style={{ ...gs.td, color:C.textMuted }}>{fmtDate(p.nascimento)}</td>
                <td style={{ ...gs.td, color:C.textMuted }}>{fmtDate(p.primeira_consulta)}</td>
                <td style={gs.td}><button onClick={e=>{e.stopPropagation();setModal(p);}} style={{ ...gs.btnOutline, padding:"6px 14px", fontSize:13 }}>Editar</button></td>
              </tr>
            ))}
            {filtered.length===0 && <tr><td colSpan={5} style={{ padding:"32px", textAlign:"center", color:C.textMuted }}>Nenhum paciente encontrado.</td></tr>}
          </tbody>
        </table>
      </div>
      {modal && <Modal title={modal==="new"?"Novo Paciente":"Editar Paciente"} onClose={()=>setModal(null)} wide><PatientForm initial={modal==="new"?{}:modal} onSave={save} onClose={()=>setModal(null)} /></Modal>}
    </div>
  );
}

function PatientDetail({ patient, consultas, pagamentos, onBack, onEdit }) {
  const pConsultas = consultas.filter(c=>c.paciente_id===patient.id).sort((a,b)=>(b.data||"").localeCompare(a.data||""));
  const pPagamentos = pagamentos.filter(p=>p.paciente_id===patient.id);
  const totalPago = pPagamentos.reduce((s,p)=>s+(p.valor_pago||0),0);
  return (
    <div>
      <button style={{ ...gs.btnOutline, marginBottom:24, fontSize:13 }} onClick={onBack}>← Voltar</button>
      <div style={{ ...gs.card, background:`linear-gradient(135deg, ${C.wineDark} 0%, ${C.wine} 100%)`, color:C.white }}>
        <div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start" }}>
          <div style={{ display:"flex", gap:20, alignItems:"center" }}>
            <div style={{ width:64, height:64, borderRadius:"50%", background:"rgba(255,255,255,0.15)", display:"flex", alignItems:"center", justifyContent:"center", fontSize:24, fontWeight:600 }}>{patient.nome?.split(" ").map(n=>n[0]).slice(0,2).join("")}</div>
            <div>
              <h2 style={{ margin:0, fontSize:24, fontFamily:"'Inter', sans-serif", fontWeight:400 }}>{patient.nome}</h2>
              <div style={{ marginTop:6, fontSize:14, opacity:0.8 }}>{patient.profissao} · {patient.celular}</div>
              <div style={{ marginTop:4, fontSize:13, opacity:0.65 }}>1ª consulta: {fmtDate(patient.primeira_consulta)} · {age(patient.nascimento)}</div>
            </div>
          </div>
          <button onClick={()=>onEdit(patient)} style={{ padding:"11px 24px", background:"rgba(255,255,255,0.2)", color:C.white, border:"1px solid rgba(255,255,255,0.3)", borderRadius:10, fontSize:13, cursor:"pointer" }}>Editar</button>
        </div>
      </div>
      <div style={gs.grid2}>
        <div style={gs.card}>
          <div style={gs.cardTitle}>Dados Pessoais</div>
          {[["Nascimento",`${fmtDate(patient.nascimento)} (${age(patient.nascimento)})`],["Estado Civil",patient.estado_civil],["Endereço",patient.endereco],["CPF",patient.cpf],["RG",patient.rg],["Contato Emergência",patient.contato_emergencia]].map(([k,v])=>v&&(
            <div key={k} style={{ display:"flex", justifyContent:"space-between", padding:"8px 0", borderBottom:`1px solid ${C.ivory}`, fontSize:14 }}>
              <span style={{ color:C.textMuted }}>{k}</span><span style={{ textAlign:"right", maxWidth:"60%" }}>{v}</span>
            </div>
          ))}
        </div>
        <div style={gs.card}>
          <div style={gs.cardTitle}>Saúde</div>
          {[["Histórico",patient.historico_medico],["Alergias",patient.alergias],["Medicamentos",patient.medicamentos],["Queixa Principal",patient.queixa_principal]].map(([k,v])=>v&&(
            <div key={k} style={{ padding:"8px 0", borderBottom:`1px solid ${C.ivory}`, fontSize:14 }}>
              <div style={{ color:C.textMuted, fontSize:12, marginBottom:2 }}>{k}</div><div>{v}</div>
            </div>
          ))}
        </div>
      </div>
      <div style={gs.card}>
        <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:20 }}>
          <div style={gs.cardTitle}>Timeline de Consultas</div>
          <div style={{ fontSize:14, color:C.wine, fontWeight:600 }}>Total pago: {fmt(totalPago)}</div>
        </div>
        {pConsultas.length===0 && <p style={{ color:C.textMuted }}>Nenhuma consulta registrada.</p>}
        {pConsultas.map((c,i)=>(
          <div key={c.id} style={{ display:"flex", gap:20, marginBottom:20 }}>
            <div style={{ display:"flex", flexDirection:"column", alignItems:"center", flexShrink:0 }}>
              <div style={{ width:12, height:12, borderRadius:"50%", background:C.gold, marginTop:4 }} />
              {i<pConsultas.length-1 && <div style={{ width:2, flex:1, background:C.sandDark, marginTop:4 }} />}
            </div>
            <div style={{ flex:1, background:C.ivory, borderRadius:12, padding:"16px" }}>
              <div style={{ display:"flex", justifyContent:"space-between", marginBottom:8 }}>
                <span style={{ fontWeight:600, fontSize:15, color:C.wine }}>{c.registro}</span>
                <span style={{ color:C.textMuted, fontSize:13 }}>{fmtDate(c.data)}</span>
              </div>
              <div style={{ marginBottom:8 }}>{(c.procedimentos||[]).map(p=><span key={p} style={gs.tag()}>{p}</span>)}</div>
              {c.descricao && <p style={{ fontSize:14, color:C.textMuted, margin:0 }}>{c.descricao}</p>}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function ConsultaForm({ initial={}, patients, onSave, onClose }) {
  const [f,setF] = useState({ registro:"",paciente_id:"",data:"",procedimentos:[],descricao:"",materiais:"",procedimentos_interesse:[],observacoes:"", ...initial });
  const set = k => e => setF(p=>({...p,[k]:e.target.value}));
  return (
    <div>
      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:20 }}>
        <Field label="Nº do Registro"><input style={gs.input} value={f.registro} onChange={set("registro")} placeholder="C-001/2024" /></Field>
        <Field label="Data da Consulta"><input type="date" style={gs.input} value={f.data} onChange={set("data")} /></Field>
        <Field label="Paciente" span={2}><select style={gs.select} value={f.paciente_id} onChange={set("paciente_id")}><option value="">Selecionar paciente...</option>{patients.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field>
        <Field label="Procedimentos Realizados" span={2}><div style={{ background:C.cream, border:`1px solid ${C.sandDark}`, borderRadius:10, padding:16 }}><Checklist options={PROCEDIMENTOS_LIST} value={f.procedimentos||[]} onChange={v=>setF(p=>({...p,procedimentos:v}))} /></div></Field>
        <Field label="Descrição" span={2}><textarea style={gs.textarea} value={f.descricao} onChange={set("descricao")} /></Field>
        <Field label="Materiais" span={2}><textarea style={gs.textarea} value={f.materiais} onChange={set("materiais")} /></Field>
        <Field label="Procedimentos de Interesse (Lead)" span={2}><div style={{ background:C.goldAlpha, border:`1px solid ${C.goldLight}`, borderRadius:10, padding:16 }}><Checklist options={PROCEDIMENTOS_LIST} value={f.procedimentos_interesse||[]} onChange={v=>setF(p=>({...p,procedimentos_interesse:v}))} /></div></Field>
        <Field label="Observações" span={2}><textarea style={gs.textarea} value={f.observacoes} onChange={set("observacoes")} /></Field>
      </div>
      <div style={{ display:"flex", gap:12, justifyContent:"flex-end", marginTop:28, borderTop:`1px solid ${C.sand}`, paddingTop:24 }}>
        <button style={gs.btnOutline} onClick={onClose}>Cancelar</button>
        <button style={gs.btn} onClick={()=>onSave(f)}>Salvar Consulta</button>
      </div>
    </div>
  );
}

function ConsultasPage({ consultas, patients, setConsultas }) {
  const [search,setSearch]=useState("");
  const [modal,setModal]=useState(null);

  const filtered = consultas.filter(c=>{
    const pac = patients.find(p=>p.id===c.paciente_id);
    return (pac?.nome||"").toLowerCase().includes(search.toLowerCase())||
      (c.registro||"").toLowerCase().includes(search.toLowerCase())||
      (c.procedimentos||[]).some(p=>p.toLowerCase().includes(search.toLowerCase()));
  }).sort((a,b)=>(b.data||"").localeCompare(a.data||""));

  const save = async (data) => {
    if(modal==="new") {
      const { data: row, error } = await supabase.from("consultas").insert([data]).select().single();
      if(!error) setConsultas(p=>[...p, row]);
    } else {
      const { error } = await supabase.from("consultas").update(data).eq("id", modal.id);
      if(!error) setConsultas(p=>p.map(x=>x.id===modal.id?{...x,...data}:x));
    }
    setModal(null);
  };

  return (
    <div>
      <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:28 }}>
        <div>
          <h1 style={{ fontSize:26, fontFamily:"'Inter', sans-serif", color:C.wine, fontWeight:400, marginBottom:4 }}>Consultas</h1>
          <p style={{ color:C.textMuted, fontSize:14 }}>{consultas.length} consultas registradas</p>
        </div>
        <button style={gs.btn} onClick={()=>setModal("new")}>+ Nova Consulta</button>
      </div>
      <div style={{ ...gs.card, marginBottom:20 }}><SearchBar value={search} onChange={setSearch} placeholder="Buscar por paciente, registro ou procedimento..." /></div>
      <div style={gs.card}>
        <table style={gs.table}>
          <thead><tr>{["Registro","Paciente","Data","Procedimentos",""].map(h=><th key={h} style={gs.th}>{h}</th>)}</tr></thead>
          <tbody>
            {filtered.map(c=>{
              const pac = patients.find(p=>p.id===c.paciente_id);
              return (
                <tr key={c.id}>
                  <td style={gs.td}><span style={gs.badge}>{c.registro}</span></td>
                  <td style={{ ...gs.td, fontWeight:500 }}>{pac?.nome||"—"}</td>
                  <td style={{ ...gs.td, color:C.textMuted }}>{fmtDate(c.data)}</td>
                  <td style={gs.td}>{(c.procedimentos||[]).slice(0,3).map(p=><span key={p} style={gs.tag()}>{p}</span>)}</td>
                  <td style={gs.td}><button onClick={()=>setModal(c)} style={{ ...gs.btnOutline, padding:"6px 14px", fontSize:13 }}>Editar</button></td>
                </tr>
              );
            })}
            {filtered.length===0 && <tr><td colSpan={5} style={{ padding:"32px", textAlign:"center", color:C.textMuted }}>Nenhuma consulta encontrada.</td></tr>}
          </tbody>
        </table>
      </div>
      {modal && <Modal title={modal==="new"?"Nova Consulta":"Editar Consulta"} onClose={()=>setModal(null)} wide><ConsultaForm initial={modal==="new"?{}:modal} patients={patients} onSave={save} onClose={()=>setModal(null)} /></Modal>}
    </div>
  );
}

function PagamentoForm({ initial={}, patients, consultas, onSave, onClose }) {
  const [f,setF] = useState({ paciente_id:"",consulta_id:"",valor_pago:0,insumos:0,aluguel:0,meios:[],observacoes:"", ...initial });
  const set = k => e => setF(p=>({...p,[k]:e.target.value}));
  const lucro = (parseFloat(f.valor_pago)||0)-(parseFloat(f.insumos)||0)-(parseFloat(f.aluguel)||0);
  const pacConsultas = consultas.filter(c=>c.paciente_id===f.paciente_id);
  return (
    <div>
      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:20 }}>
        <Field label="Paciente" span={2}><select style={gs.select} value={f.paciente_id} onChange={e=>setF(p=>({...p,paciente_id:e.target.value,consulta_id:""}))}><option value="">Selecionar paciente...</option>{patients.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field>
        <Field label="Consulta" span={2}><select style={gs.select} value={f.consulta_id} onChange={set("consulta_id")}><option value="">Selecionar consulta...</option>{pacConsultas.map(c=><option key={c.id} value={c.id}>{c.registro} — {fmtDate(c.data)}</option>)}</select></Field>
        <Field label="Valor Pago (R$)"><input type="number" style={gs.input} value={f.valor_pago} onChange={set("valor_pago")} min={0} step={0.01} /></Field>
        <Field label="Insumos (R$)"><input type="number" style={gs.input} value={f.insumos} onChange={set("insumos")} min={0} step={0.01} /></Field>
        <Field label="Aluguel da Sala (R$)"><input type="number" style={gs.input} value={f.aluguel} onChange={set("aluguel")} min={0} step={0.01} /></Field>
        <Field label="Lucro (Calculado)"><div style={{ ...gs.input, background: lucro>=0?C.successBg:C.dangerBg, color: lucro>=0?C.success:C.danger, fontWeight:600 }}>{fmt(lucro)}</div></Field>
        <Field label="Meio de Pagamento" span={2}><div style={{ background:C.cream, border:`1px solid ${C.sandDark}`, borderRadius:10, padding:16 }}><Checklist options={MEIOS_PAGAMENTO} value={f.meios||[]} onChange={v=>setF(p=>({...p,meios:v}))} columns={3} /></div></Field>
        <Field label="Observações" span={2}><textarea style={gs.textarea} value={f.observacoes} onChange={set("observacoes")} /></Field>
      </div>
      <div style={{ display:"flex", gap:12, justifyContent:"flex-end", marginTop:28, borderTop:`1px solid ${C.sand}`, paddingTop:24 }}>
        <button style={gs.btnOutline} onClick={onClose}>Cancelar</button>
        <button style={gs.btn} onClick={()=>onSave({...f,valor_pago:parseFloat(f.valor_pago)||0,insumos:parseFloat(f.insumos)||0,aluguel:parseFloat(f.aluguel)||0})}>Salvar Pagamento</button>
      </div>
    </div>
  );
}

function PagamentosPage({ pagamentos, patients, consultas, setPagamentos }) {
  const [modal,setModal]=useState(null);
  const totalReceita = pagamentos.reduce((s,p)=>s+(p.valor_pago||0),0);
  const totalInsumos = pagamentos.reduce((s,p)=>s+(p.insumos||0),0);
  const totalAluguel = pagamentos.reduce((s,p)=>s+(p.aluguel||0),0);
  const totalLucro = totalReceita-totalInsumos-totalAluguel;

  const save = async (data) => {
    if(modal==="new") {
      const { data: row, error } = await supabase.from("pagamentos").insert([data]).select().single();
      if(!error) setPagamentos(p=>[...p, row]);
    } else {
      const { error } = await supabase.from("pagamentos").update(data).eq("id", modal.id);
      if(!error) setPagamentos(p=>p.map(x=>x.id===modal.id?{...x,...data}:x));
    }
    setModal(null);
  };

  return (
    <div>
      <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:28 }}>
        <div><h1 style={{ fontSize:26, fontFamily:"'Inter', sans-serif", color:C.wine, fontWeight:400, marginBottom:4 }}>Pagamentos</h1><p style={{ color:C.textMuted, fontSize:14 }}>{pagamentos.length} registros</p></div>
        <button style={gs.btn} onClick={()=>setModal("new")}>+ Novo Pagamento</button>
      </div>
      <div style={gs.grid4}>
        {[{l:"Receita",v:totalReceita,c:C.wine},{l:"Insumos",v:totalInsumos,c:C.textMuted},{l:"Aluguel",v:totalAluguel,c:C.textMuted},{l:"Lucro",v:totalLucro,c:C.success}].map(s=>(
          <div key={s.l} style={gs.statCard}><div style={{ ...gs.statNum, color:s.c, fontSize:20 }}>{fmt(s.v)}</div><div style={gs.statLabel}>{s.l}</div></div>
        ))}
      </div>
      <div style={{ ...gs.card, marginTop:20 }}>
        <table style={gs.table}>
          <thead><tr>{["Paciente","Consulta","Valor","Insumos","Aluguel","Lucro","Meio",""].map(h=><th key={h} style={gs.th}>{h}</th>)}</tr></thead>
          <tbody>
            {[...pagamentos].reverse().map(pg=>{
              const pac = patients.find(p=>p.id===pg.paciente_id);
              const con = consultas.find(c=>c.id===pg.consulta_id);
              const lucro = (pg.valor_pago||0)-(pg.insumos||0)-(pg.aluguel||0);
              return (
                <tr key={pg.id}>
                  <td style={{ ...gs.td, fontWeight:500 }}>{pac?.nome||"—"}</td>
                  <td style={{ ...gs.td, color:C.textMuted }}>{con?.registro||"—"}</td>
                  <td style={gs.td}><strong style={{ color:C.wine }}>{fmt(pg.valor_pago)}</strong></td>
                  <td style={{ ...gs.td, color:C.textMuted }}>{fmt(pg.insumos)}</td>
                  <td style={{ ...gs.td, color:C.textMuted }}>{fmt(pg.aluguel)}</td>
                  <td style={gs.td}><strong style={{ color: lucro>=0?C.success:C.danger }}>{fmt(lucro)}</strong></td>
                  <td style={gs.td}>{(pg.meios||[]).map(m=><span key={m} style={gs.tag("gold")}>{m}</span>)}</td>
                  <td style={gs.td}><button onClick={()=>setModal(pg)} style={{ ...gs.btnOutline, padding:"6px 14px", fontSize:13 }}>Editar</button></td>
                </tr>
              );
            })}
            {pagamentos.length===0 && <tr><td colSpan={8} style={{ padding:"32px", textAlign:"center", color:C.textMuted }}>Nenhum pagamento ainda.</td></tr>}
          </tbody>
        </table>
      </div>
      {modal && <Modal title={modal==="new"?"Novo Pagamento":"Editar Pagamento"} onClose={()=>setModal(null)} wide><PagamentoForm initial={modal==="new"?{}:modal} patients={patients} consultas={consultas} onSave={save} onClose={()=>setModal(null)} /></Modal>}
    </div>
  );
}

function LeadForm({ initial={}, onSave, onClose }) {
  const [f,setF] = useState({ nome:"",data_contato:"",meio_contato:"Instagram",sexo:"Feminino",celular:"",profissao:"",procedimentos_interesse:[],motivo_nao_fechar:"",nivel_interesse:"",queixa_principal:"",proximo_contato:"",observacoes:"", ...initial });
  const set = k => e => setF(p=>({...p,[k]:e.target.value}));
  return (
    <div>
      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:20 }}>
        <Field label="Nome Completo" span={2}><input style={gs.input} value={f.nome} onChange={set("nome")} /></Field>
        <Field label="Data do Contato"><input type="date" style={gs.input} value={f.data_contato} onChange={set("data_contato")} /></Field>
        <Field label="Próximo Contato"><input type="date" style={gs.input} value={f.proximo_contato} onChange={set("proximo_contato")} /></Field>
        <Field label="Meio de Contato"><select style={gs.select} value={f.meio_contato} onChange={set("meio_contato")}>{MEIOS_CONTATO.map(m=><option key={m}>{m}</option>)}</select></Field>
        <Field label="Sexo"><select style={gs.select} value={f.sexo} onChange={set("sexo")}><option>Feminino</option><option>Masculino</option><option>Outro</option></select></Field>
        <Field label="Celular"><input style={gs.input} value={f.celular} onChange={set("celular")} /></Field>
        <Field label="Profissão"><input style={gs.input} value={f.profissao} onChange={set("profissao")} /></Field>
        <Field label="Nível de Interesse" span={2}><input style={gs.input} value={f.nivel_interesse} onChange={set("nivel_interesse")} placeholder="Alto / Médio / Baixo" /></Field>
        <Field label="Procedimentos de Interesse" span={2}><div style={{ background:C.cream, border:`1px solid ${C.sandDark}`, borderRadius:10, padding:16 }}><Checklist options={PROCEDIMENTOS_LIST} value={f.procedimentos_interesse||[]} onChange={v=>setF(p=>({...p,procedimentos_interesse:v}))} /></div></Field>
        <Field label="Queixa Principal" span={2}><textarea style={gs.textarea} value={f.queixa_principal} onChange={set("queixa_principal")} /></Field>
        <Field label="Motivo de não fechar agora" span={2}><textarea style={gs.textarea} value={f.motivo_nao_fechar} onChange={set("motivo_nao_fechar")} /></Field>
        <Field label="Observações" span={2}><textarea style={gs.textarea} value={f.observacoes} onChange={set("observacoes")} /></Field>
      </div>
      <div style={{ display:"flex", gap:12, justifyContent:"flex-end", marginTop:28, borderTop:`1px solid ${C.sand}`, paddingTop:24 }}>
        <button style={gs.btnOutline} onClick={onClose}>Cancelar</button>
        <button style={gs.btn} onClick={()=>onSave(f)}>Salvar Lead</button>
      </div>
    </div>
  );
}

function LeadsPage({ leads, setLeads }) {
  const [search,setSearch]=useState("");
  const [modal,setModal]=useState(null);
  const filtered = leads.filter(l=>l.nome?.toLowerCase().includes(search.toLowerCase())||l.celular?.includes(search));

  const save = async (data) => {
    if(modal==="new") {
      const { data: row, error } = await supabase.from("leads").insert([data]).select().single();
      if(!error) setLeads(p=>[...p, row]);
    } else {
      const { error } = await supabase.from("leads").update(data).eq("id", modal.id);
      if(!error) setLeads(p=>p.map(x=>x.id===modal.id?{...x,...data}:x));
    }
    setModal(null);
  };

  const nivelColor = (n) => {
    if(!n) return {};
    if(n.toLowerCase().includes("alt")) return { background:C.successBg, color:C.success };
    if(n.toLowerCase().includes("méd")||n.toLowerCase().includes("med")) return { background:C.goldAlpha, color:C.wine };
    return { background:C.dangerBg, color:C.danger };
  };

  return (
    <div>
      <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:28 }}>
        <div><h1 style={{ fontSize:26, fontFamily:"'Inter', sans-serif", color:C.wine, fontWeight:400, marginBottom:4 }}>Leads</h1><p style={{ color:C.textMuted, fontSize:14 }}>{leads.length} leads</p></div>
        <button style={gs.btn} onClick={()=>setModal("new")}>+ Novo Lead</button>
      </div>
      <div style={{ ...gs.card, marginBottom:20 }}><SearchBar value={search} onChange={setSearch} placeholder="Buscar leads..." /></div>
      <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:20 }}>
        {filtered.map(l=>(
          <div key={l.id} style={{ ...gs.card, margin:0, cursor:"pointer" }} onClick={()=>setModal(l)}>
            <div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:12 }}>
              <div><div style={{ fontWeight:600, fontSize:16 }}>{l.nome}</div><div style={{ fontSize:12, color:C.textMuted, marginTop:2 }}>{l.meio_contato} · {fmtDate(l.data_contato)}</div></div>
              {l.nivel_interesse && <span style={{ ...nivelColor(l.nivel_interesse), padding:"3px 10px", borderRadius:20, fontSize:12, fontWeight:500 }}>{l.nivel_interesse}</span>}
            </div>
            <div>{(l.procedimentos_interesse||[]).slice(0,3).map(p=><span key={p} style={gs.tag("gold")}>{p}</span>)}</div>
            {l.proximo_contato && <div style={{ fontSize:12, color:C.textMuted, marginTop:8, borderTop:`1px solid ${C.sand}`, paddingTop:8 }}>📅 Próximo contato: <strong>{fmtDate(l.proximo_contato)}</strong></div>}
          </div>
        ))}
        {filtered.length===0 && <div style={{ gridColumn:"1/-1", padding:"32px", textAlign:"center", color:C.textMuted }}>Nenhum lead encontrado.</div>}
      </div>
      {modal && <Modal title={modal==="new"?"Novo Lead":"Editar Lead"} onClose={()=>setModal(null)} wide><LeadForm initial={modal==="new"?{}:modal} onSave={save} onClose={()=>setModal(null)} /></Modal>}
    </div>
  );
}

function Login({ onLogin }) {
  const [u,setU]=useState(""); const [p,setP]=useState(""); const [err,setErr]=useState(false);
  const USERS = [
    { user: "dra.victoriaghisolfi", password: "Hannah1998." },
    { user: "gabrielandradedearaujo", password: "trophyhusband123" },
    { user: "auxiliar", password: "clinicaghisolfi26" },
  ];
  const submit = () => {
    if(USERS.some(x=>x.user===u && x.password===p)) onLogin();
    else setErr(true);
  };
  return (
    <div style={{ minHeight:"100vh", background:`linear-gradient(135deg, ${C.wineDark} 0%, ${C.wine} 50%, ${C.wineLight} 100%)`, display:"flex", alignItems:"center", justifyContent:"center" }}>
      <div style={{ background:C.white, borderRadius:24, padding:"48px 56px", width:420, boxShadow:"0 40px 100px rgba(44,31,37,0.35)" }}>
        <div style={{ textAlign:"center", marginBottom:36 }}>
          <img src={`data:image/png;base64,${LOGO_B64}`} alt="Logo VG" style={{ width:220, display:"block", margin:"0 auto 4px" }} />
          <h1 style={{ fontFamily:"'Playfair Display', serif", fontSize:20, color:C.wine, fontWeight:600, letterSpacing:3, margin:0, textTransform:"uppercase" }}>CLÍNICA GHISOLFI</h1>
          <div style={{ fontSize:11, color:C.gold, letterSpacing:4, marginTop:6, textTransform:"uppercase" }}>Estética & Odontologia</div>
        </div>
        <Field label="Usuário"><input style={gs.input} value={u} onChange={e=>setU(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} /></Field>
        <div style={{ marginTop:16 }}><Field label="Senha"><input type="password" style={gs.input} value={p} onChange={e=>setP(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} /></Field></div>
        {err && <p style={{ color:C.danger, fontSize:13, marginTop:8, textAlign:"center" }}>Credenciais inválidas.</p>}
        <button style={{ ...gs.btn, width:"100%", marginTop:24, padding:"14px" }} onClick={submit}>Entrar</button>
      </div>
    </div>
  );
}

export default function App() {
  const [logged,setLogged]=useState(false);
  const [nav,setNav]=useState("dashboard");
  const [patients,setPatients]=useState([]);
  const [consultas,setConsultas]=useState([]);
  const [pagamentos,setPagamentos]=useState([]);
  const [leads,setLeads]=useState([]);
  const [loading,setLoading]=useState(false);

  useEffect(() => {
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Playfair+Display:wght@400;500;600;700&display=swap";
    document.head.appendChild(link);
  }, []);

  useEffect(() => {
    if(!logged) return;
    setLoading(true);
    Promise.all([
      supabase.from("pacientes").select("*").order("created_at", { ascending: false }),
      supabase.from("consultas").select("*").order("created_at", { ascending: false }),
      supabase.from("pagamentos").select("*").order("created_at", { ascending: false }),
      supabase.from("leads").select("*").order("created_at", { ascending: false }),
    ]).then(([p,c,pg,l]) => {
      setPatients(p.data||[]);
      setConsultas(c.data||[]);
      setPagamentos(pg.data||[]);
      setLeads(l.data||[]);
      setLoading(false);
    });
  }, [logged]);

  if(!logged) return <Login onLogin={()=>setLogged(true)} />;
  if(loading) return <LoadingScreen />;

  const navItems = [
    { id:"dashboard", label:"Dashboard", icon:"🏠" },
    { id:"pacientes", label:"Pacientes", icon:"👤" },
    { id:"consultas", label:"Consultas", icon:"📋" },
    { id:"pagamentos", label:"Pagamentos", icon:"💰" },
    { id:"leads", label:"Leads", icon:"✨" },
  ];

  const pageTitle = { dashboard:"Dashboard", pacientes:"Pacientes", consultas:"Consultas", pagamentos:"Financeiro", leads:"Leads" };

  return (
    <div style={gs.app}>
      <div style={gs.sidebar}>
        <div style={gs.logo}>
          <img src={`data:image/png;base64,${LOGO_B64}`} alt="Logo VG" style={{ width:180, display:"block", marginBottom:2 }} />
          <div style={gs.logoTitle}>CLÍNICA GHISOLFI</div>
          <div style={gs.logoSub}>ESTÉTICA & ODONTO</div>
        </div>
        <div style={{ marginTop:16 }}>
          <div style={gs.navLabel}>Menu</div>
          {navItems.map(item=>(
            <div key={item.id} style={gs.navItem(nav===item.id)} onClick={()=>setNav(item.id)}>
              <span style={{ fontSize:16 }}>{item.icon}</span>
              <span>{item.label}</span>
              {item.id==="leads" && leads.length>0 && <span style={{ marginLeft:"auto", background:C.gold, color:C.white, borderRadius:20, padding:"2px 7px", fontSize:11, fontWeight:600 }}>{leads.length}</span>}
            </div>
          ))}
        </div>
        <div style={{ marginTop:"auto", padding:"0 24px" }}>
          <button onClick={()=>setLogged(false)} style={{ width:"100%", padding:"10px", background:"rgba(255,255,255,0.06)", border:"1px solid rgba(255,255,255,0.1)", borderRadius:10, color:"rgba(255,255,255,0.5)", cursor:"pointer", fontSize:13 }}>Sair</button>
        </div>
      </div>
      <div style={gs.main}>
        <div style={gs.topbar}>
          <div style={{ fontFamily:"'Playfair Display', serif", fontSize:18, color:C.wine, fontWeight:600, textTransform:"uppercase", letterSpacing:2 }}>{pageTitle[nav]}</div>
          <div style={{ display:"flex", alignItems:"center", gap:16 }}>
            <span style={{ fontSize:14, color:C.textMuted }}>{patients.length} pacientes · {consultas.length} consultas</span>
            <div style={{ width:36, height:36, borderRadius:"50%", background:C.wineAlpha, display:"flex", alignItems:"center", justifyContent:"center", fontSize:14, color:C.wine, fontWeight:600 }}>VG</div>
          </div>
        </div>
        <div style={gs.content}>
          {nav==="dashboard" && <Dashboard patients={patients} consultas={consultas} pagamentos={pagamentos} leads={leads} onNav={setNav} />}
          {nav==="pacientes" && <PatientsPage patients={patients} consultas={consultas} pagamentos={pagamentos} setPatients={setPatients} />}
          {nav==="consultas" && <ConsultasPage consultas={consultas} patients={patients} setConsultas={setConsultas} />}
          {nav==="pagamentos" && <PagamentosPage pagamentos={pagamentos} patients={patients} consultas={consultas} setPagamentos={setPagamentos} />}
          {nav==="leads" && <LeadsPage leads={leads} setLeads={setLeads} />}
        </div>
      </div>
    </div>
  );
}
